window.ruleDemoData = {
  rulesBase: [
    {
      "rule_id": "R001",
      "name": "女生别太拼",
      "must_include_any": ["女生", "女孩", "女人", "女的"],
      "must_include_any_2": ["别太拼", "不用太拼", "别那么拼", "别太努力", "不用那么努力","不用工作"],
      "exclude_any": [],
      "labels": ["职业/能力偏见", "家庭角色期待"],
      "severity_default": "medium",
      "confidence_default": "high",
      "surface_meaning_template": "说话者表面上是在劝对方不要过度努力或竞争。",
      "hidden_structure_template": "这句话可能默认女性不需要高度投入事业或竞争，或者最终应把重心放回家庭。",
      "impact_template": "可能削弱女性对事业目标的正当感，让野心显得“不合适”。",
      "gentle_response": "我理解你的意思，不过我也很重视自己的发展。",
      "boundary_response": "我不太认同女生就不该努力这个说法。",
      "question_response": "为什么你会觉得女生不应该太拼？",
      "notes": "适合与职业、学习、晋升、竞争等词同时出现时提高置信度。",
      "priority": 100,
      "contexts": []
    },
    {
      "rule_id": "R002",
      "name": "女生不适合领导/技术",
      "must_include_any": ["女生", "女孩", "女人", "女的"],
      "must_include_any_2": ["不适合当领导", "不适合做技术", "不适合搞技术", "当不了领导" ,"做不了领导", "逻辑不行", "理科不行", "脑子笨", "脑子不行", "脑子不好使", "什么都不懂", "不能当班长", "不适合当班长", "女生当不了班长"],
      "exclude_any": [],
      "labels": ["职业/能力偏见"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在判断女性在某类能力或岗位上的适配性。",
      "hidden_structure_template": "这句话把能力差异天然化，把性别当成决定职业能力和领导力的依据。",
      "impact_template": "可能限制女性进入高权力、高技术或高薪岗位。",
      "gentle_response": "能力还是要看个人，而不是只看性别。",
      "boundary_response": "把岗位适配性直接和性别绑定并不合理。",
      "question_response": "你为什么认为这些能力和性别天然相关？",
      "notes": "和“领导、技术、理工、逻辑、编程、管理”共现时更强。",
      "priority": 99,
      "contexts": []
    },
    {
      "rule_id": "R003",
      "name": "女生还是要顾家",
      "must_include_any": ["女生", "女孩", "女人", "媳妇", "老婆"],
      "must_include_any_2": ["顾家", "照顾家庭", "带孩子", "会做饭", "贤惠", "持家", "照顾老人"],
      "exclude_any": [],
      "labels": ["家庭角色期待"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在强调女性应承担家庭照顾责任。",
      "hidden_structure_template": "这句话把照护劳动默认分配给女性，把家庭责任性别化。",
      "impact_template": "可能让照护、家务和婚育责任被视为女性的天然义务。",
      "gentle_response": "家庭责任其实可以由伴侣共同承担。",
      "boundary_response": "我不认同把顾家默认成女性的责任。",
      "question_response": "为什么这些家庭责任默认应该由女性承担？",
      "notes": "婚恋、孩子、家务、做饭语境下常见。",
      "priority": 98,
      "contexts": []
    },
    {
      "rule_id": "R004",
      "name": "女孩不用赚太多",
      "must_include_any": ["女生", "女孩", "女人"],
      "must_include_any_2": ["不用赚太多", "没必要赚那么多", "找个好老公就行", "嫁得好更重要", "赚钱不是最重要", "女生少花点钱", "女孩少花点钱", "别花那么多钱", "女孩子少花点钱", "花钱别太大手大脚", "找个男人就好了", "找个男人就行了"],
      "exclude_any": ["女生要独立", "女孩要独立", "女人要独立", "女生要自己买房", "女孩要自己买房", "经济独立很重要"],
      "labels": ["经济依附期待", "家庭角色期待"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在淡化女性的经济独立和职业追求。",
      "hidden_structure_template": "这句话可能默认女性可以依附婚姻或男性资源，而不是把经济自主当作核心能力。",
      "impact_template": "可能削弱女性对经济独立的重视，强化依附关系。",
      "gentle_response": "对我来说，经济独立还是很重要。",
      "boundary_response": "我不接受把女性的人生价值建立在依附别人上。",
      "question_response": "为什么你觉得女性不需要追求经济独立？",
      "notes": "更偏“经济依附期待/婚姻替代独立”，不主打能力贬低。",
      "priority": 97,
      "contexts": []
    },
    {
      "rule_id": "R005",
      "name": "你这样不像女生",
      "must_include_any": ["不像女生", "不像个女生", "不够女人", "没有女人味", "不像女孩"],
      "must_include_any_2": [],
      "exclude_any": [],
      "labels": ["性别角色规范", "外貌/气质规训"],
      "severity_default": "medium",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在评价某种行为、外表或气质不符合其认定的女性标准。",
      "hidden_structure_template": "这句话把女性限定在固定的气质、外表或行为模式里。",
      "impact_template": "可能让女性因不符合“标准女性形象”而感到被纠正或羞耻。",
      "gentle_response": "每个人表达自己的方式都不一样。",
      "boundary_response": "我不觉得女生必须长成或表现成某一种样子。",
      "question_response": "什么叫“像女生”？这个标准是谁定的？",
      "notes": "适合与穿衣、说话、发型、兴趣等语境联动。",
      "priority": 96,
      "contexts": []
    },
    {
      "rule_id": "R006",
      "name": "女生就该温柔/懂事",
      "must_include_any": ["女生", "女孩", "女人"],
      "must_include_any_2": ["温柔", "懂事", "听话", "贤惠", "乖一点", "别那么凶", "不要太调皮", "别太调皮", "不要有主见", "别有主见", "不要太有想法", "别太有想法", "别太有主意", "不要太有主意"],
      "exclude_any": [],
      "labels": ["顺从规训", "性别角色规范"],
      "severity_default": "medium",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在要求女性以更顺从、柔和、可管理的方式表现自己。",
      "hidden_structure_template": "这句话可能在用性别规范约束女性的表达边界，让女性更易被管理和评价。",
      "impact_template": "可能压缩女性表达愤怒、坚持立场和直接沟通的空间。",
      "gentle_response": "我可以保持尊重，但也会清楚表达自己的想法。",
      "boundary_response": "我不认为女性就该更顺从或更好管理。",
      "question_response": "为什么这些要求只更常落在女性身上？",
      "notes": "更偏“顺从/听话/别太有主意”的服从规训，不主打婚恋惩罚。",
      "priority": 95,
      "contexts": []
    },
    {
      "rule_id": "R007",
      "name": "你太强势了",
      "must_include_any": ["太强势", "别那么强势", "太有攻击性", "咄咄逼人"],
      "must_include_any_2": [],
      "exclude_any": [],
      "labels": ["权力/服从结构"],
      "severity_default": "medium",
      "confidence_default": "medium",
      "surface_meaning_template": "说话者在评价对方表达立场的方式过于强硬。",
      "hidden_structure_template": "在女性语境中，这类评价常被用来惩罚清晰表达、自我主张或权力竞争。",
      "impact_template": "可能让女性在表达领导力或边界时被迫自我收缩。",
      "gentle_response": "我只是在清楚表达自己的立场。",
      "boundary_response": "我不接受把明确表达意见直接等同于“强势”或问题化。",
      "question_response": "如果是男性这样表达，你也会用同样的词吗？",
      "notes": "需结合女性主体语境；否则应降为“可能”。",
      "priority": 94,
      "contexts": []
    },
    {
      "rule_id": "R008",
      "name": "你太敏感/情绪化了",
      "must_include_any": ["太敏感", "想太多", "太情绪化", "玻璃心", "小题大做", "脾气差"],
      "must_include_any_2": [],
      "exclude_any": [],
      "labels": ["情绪压制", "认知贬低"],
      "severity_default": "medium",
      "confidence_default": "medium",
      "surface_meaning_template": "说话者在否定对方对某句话或某件事的不适反应。",
      "hidden_structure_template": "这类表达可能把合理的不适或批评重新定义成个人情绪问题，从而回避结构性问题。",
      "impact_template": "可能让女性在指出冒犯、偏见或不公平时被去正当化。",
      "gentle_response": "我不是在夸张，我是在表达这句话带来的真实感受。",
      "boundary_response": "请不要用“敏感”来否定我提出的问题。",
      "question_response": "你是在回应我说的问题，还是在评价我的情绪？",
      "notes": "需要结合具体上下文，避免把普通安慰都判成压制。",
      "priority": 93,
      "contexts": []
    },
    {
      "rule_id": "R009",
      "name": "女生开车不行",
      "must_include_any": ["女生", "女司机", "女人"],
      "must_include_any_2": ["开车不行", "开车差", "不会开车", "车技差"],
      "exclude_any": [],
      "labels": ["能力刻板印象"],
      "severity_default": "medium",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把某类技能水平直接归因于性别。",
      "hidden_structure_template": "这句话通过重复刻板印象，把个体差异硬套成性别差异。",
      "impact_template": "会强化对女性能力的低估和公开嘲讽。",
      "gentle_response": "驾驶技术还是看个人经验和训练。",
      "boundary_response": "把能力问题直接归到性别上并不合理。",
      "question_response": "你有依据证明这和性别天然相关吗？",
      "notes": "适用于驾驶、数学、理财、领导等能力模板扩展。",
      "priority": 92,
      "contexts": []
    },
    {
      "rule_id": "R010",
      "name": "女生数学/理科差",
      "must_include_any": ["女生", "女孩", "女人"],
      "must_include_any_2": ["数学差", "理科差", "不适合理工", "不适合编程", "逻辑差", "脑子笨", "脑子不好使", "脑子转得慢","不会用电脑","不会写代码"],
      "exclude_any": [],
      "labels": ["职业/能力偏见", "能力刻板印象"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把学科能力差异解释为性别特质。",
      "hidden_structure_template": "这句话通过“天生差异”的说法，压低女性在知识和技术领域的进入门槛与自信。",
      "impact_template": "可能影响女性的学习选择、职业路径和自我效能感。",
      "gentle_response": "学习能力不能直接用性别概括。",
      "boundary_response": "把理工能力直接和性别绑定是偏见。",
      "question_response": "为什么你认为这是性别差异，而不是个体和环境差异？",
      "notes": "与教育和职业建议场景常见。",
      "priority": 91,
      "contexts": []
    },
    {
      "rule_id": "R011",
      "name": "长得好看更重要",
      "must_include_any": ["女生", "女孩", "女人"],
      "must_include_any_2": ["长得好看更重要", "漂亮最重要", "颜值就是资本", "女生要会打扮", "打扮一下更像女生", "女生要瘦一点", "女孩要瘦一点", "女生就爱减肥", "女生要漂亮", "女生要美", "女孩要漂亮", "女孩要美", "女生不能胖", "女孩不能胖", "女人不能胖", "女生不可以胖"],
      "exclude_any": ["健康减肥", "科学减肥", "医生建议减重", "营养管理"],
      "labels": ["外貌价值绑定", "服美役规训", "物化"],
      "severity_default": "medium",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在强调女性外貌的重要性。",
      "hidden_structure_template": "这句话把女性价值与可被观看、评价和消费的外表联系起来。",
      "impact_template": "可能强化外貌焦虑和以被评价为中心的自我认同。",
      "gentle_response": "外表可以是表达的一部分，但不该定义一个人的价值。",
      "boundary_response": "我不接受把女性价值主要放在外貌上。",
      "question_response": "为什么女性总是更容易被要求先满足外貌标准？",
      "notes": "更偏“女性价值优先建立在好看、变美、会打扮上”，不主打饮食规训或婚恋惩罚。",
      "priority": 90,
      "contexts": []
    },
    {
      "rule_id": "R012",
      "name": "再胖就没人要了",
      "must_include_any": ["胖", "瘦", "减肥", "身材"],
      "must_include_any_2": ["没人要", "不好找对象", "嫁不出去", "不像女生", "吃这么多会胖", "女生还是少吃点", "女孩还是少吃点", "女生吃太多不好", "女孩子吃太多不好"],
      "exclude_any": ["好好吃饭", "按时吃饭", "正常吃饭", "多吃点身体才好", "健康饮食"],
      "labels": ["身体羞辱", "婚恋价值绑定"],
      "severity_default": "high",
      "confidence_default": "medium",
      "surface_meaning_template": "说话者在用婚恋价值评价女性的身体状态。",
      "hidden_structure_template": "这句话把女性身体当成被选择和被评价的对象，并把外形与婚恋可得性绑定。",
      "impact_template": "可能加剧身体羞耻、饮食压力和自我物化。",
      "gentle_response": "我的身体不应该只用来满足他人的评价标准。",
      "boundary_response": "请不要用婚恋价值来评价我的身材。",
      "question_response": "为什么女性的身体总要和“能不能被选择”绑定？",
      "notes": "更偏“胖了就没人要/不好嫁”的婚恋惩罚，不主打一般饮食规训。",
      "priority": 89,
      "contexts": []
    },
    {
      "rule_id": "R013",
      "name": "年纪大了就不好找对象",
      "must_include_any": ["年纪大", "年龄大", "三十了", "三十多了", "老了"],
      "must_include_any_2": ["不好找对象", "嫁不出去", "抓紧结婚", "赶紧生孩子", "总是要结婚", "女生总归要结婚", "女孩总归要结婚", "女人总会结婚", "女生总会结婚", "女孩总会结婚"],
      "exclude_any": [],
      "labels": ["婚育时钟规训", "家庭角色期待"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在提醒或施压女性要按特定年龄节点完成婚育。",
      "hidden_structure_template": "这句话把女性人生路径收束到婚育时间表上，并把年龄视为对女性更严厉的价值倒计时。",
      "impact_template": "可能制造年龄焦虑和婚育压力。",
      "gentle_response": "每个人的人生节奏不一样，我更希望按自己的规划来。",
      "boundary_response": "我不接受把女性的人生价值缩减成婚育时间表。",
      "question_response": "为什么年龄压力主要更集中地落在女性身上？",
      "notes": "和相亲、家庭催婚语境高度相关。",
      "priority": 88,
      "contexts": []
    },
    {
      "rule_id": "R014",
      "name": "女生谈太多恋爱不好",
      "must_include_any": ["女生", "女孩", "女人"],
      "must_include_any_2": ["谈太多恋爱不好", "太随便", "不检点", "名声不好", "女孩要矜持","玩的花"],
      "exclude_any": [],
      "labels": ["性/亲密关系控制", "双重标准"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在用道德标准约束女性的亲密关系行为。",
      "hidden_structure_template": "这句话常体现对女性性与亲密关系的更严格规训，同时默认男性可被更宽松对待。",
      "impact_template": "可能加强羞耻感、双重标准和名誉控制。",
      "gentle_response": "亲密关系的选择应该建立在尊重和自愿上，而不是单一性别标准上。",
      "boundary_response": "我不接受只对女性适用的道德双重标准。",
      "question_response": "如果是男性经历相同的事，你也会这样评价吗？",
      "notes": "和“矜持、名声、体面、纯洁”共现时更强。",
      "priority": 87,
      "contexts": []
    },
    {
      "rule_id": "R015",
      "name": "女生不要主动",
      "must_include_any": ["女生", "女孩", "女人"],
      "must_include_any_2": ["不要太主动", "别主动", "要矜持", "太主动不好", "女追男不好"],
      "exclude_any": [],
      "labels": ["性/亲密关系控制", "权力/服从结构"],
      "severity_default": "medium",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在限制女性在亲密关系中的行动和表达。",
      "hidden_structure_template": "这句话默认恋爱中的主动权更适合掌握在男性手中，女性应处于被选择位置。",
      "impact_template": "可能削弱女性在关系中的主体性和表达自由。",
      "gentle_response": "主动表达并不等于失去分寸。",
      "boundary_response": "我不接受把女性固定在被动的位置上。",
      "question_response": "为什么亲密关系中的主动权默认不属于女性？",
      "notes": "恋爱、追求、约会语境常见。",
      "priority": 86,
      "contexts": []
    },
    {
      "rule_id": "R016",
      "name": "都是当妈的人了",
      "must_include_any": ["当妈", "妈妈", "做母亲", "有孩子了"],
      "must_include_any_2": ["别这样", "该稳重点", "该把重心放家里", "要为孩子考虑"],
      "exclude_any": [],
      "labels": ["母职规训", "家庭角色期待"],
      "severity_default": "high",
      "confidence_default": "medium",
      "surface_meaning_template": "说话者在用母亲身份限制女性的行为或生活选择。",
      "hidden_structure_template": "这句话把母亲角色扩张成女性整体身份，要求她围绕照护责任重新定义自己。",
      "impact_template": "可能压缩母亲作为独立个体的兴趣、事业和行动空间。",
      "gentle_response": "成为母亲并不意味着我只能有一种身份。",
      "boundary_response": "请不要用母亲身份来否定我其他合理的选择。",
      "question_response": "为什么做母亲就必须放弃个人空间或目标？",
      "notes": "需结合 motherhood 语境。",
      "priority": 85,
      "contexts": []
    },
    {
      "rule_id": "R017",
      "name": "女强人都不幸福",
      "must_include_any": ["女强人"],
      "must_include_any_2": ["不幸福", "没人要", "婚姻不好", "家庭不幸福"],
      "exclude_any": [],
      "labels": ["职业/能力偏见", "婚恋惩罚叙事"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在用幸福或婚恋结果惩罚女性的事业成功。",
      "hidden_structure_template": "这句话传达的是：女性一旦拥有权力、成就或独立，就要为此在亲密关系中“付代价”。",
      "impact_template": "可能让女性把成功和失去爱绑定起来。",
      "gentle_response": "事业成功和关系幸福并不是天然对立的。",
      "boundary_response": "我不接受用“幸福”来惩罚女性的独立和成就。",
      "question_response": "为什么同样的成功在男性身上常被夸赞，在女性身上却被视作代价？",
      "notes": "和婚恋评价、成功惩罚叙事相关。",
      "priority": 84,
      "contexts": []
    },
    {
      "rule_id": "R018",
      "name": "老婆/女友就该支持我",
      "must_include_any": ["老婆", "女友", "妻子", "对象"],
      "must_include_any_2": ["就该支持我", "应该体谅我", "别给我添麻烦", "以我事业为主"],
      "exclude_any": [],
      "labels": ["权力/服从结构", "关系中的资源不对称"],
      "severity_default": "medium",
      "confidence_default": "medium",
      "surface_meaning_template": "说话者在强调伴侣应优先支持自己的目标和安排。",
      "hidden_structure_template": "在异性关系语境中，这类表达可能默认女性伴侣应作为支持者而非平等行动者存在。",
      "impact_template": "可能使伴侣关系中的时间、机会与情绪劳动分配失衡。",
      "gentle_response": "互相支持很重要，但关系也需要双向考虑。",
      "boundary_response": "我不接受只要求一方长期让步的关系模式。",
      "question_response": "为什么默认是她来配合，而不是共同协商？",
      "notes": "需结合具体关系语境判断。",
      "priority": 83,
      "contexts": []
    },
    {
      "rule_id": "R019",
      "name": "女生不要穿太暴露",
      "must_include_any": ["女生", "女孩", "女人"],
      "must_include_any_2": ["别穿太暴露", "穿这么短", "穿成这样", "注意点形象", "容易出事", "穿得太少", "穿这么少", "穿太露了", "露太多了", "别穿这么露", "穿得这么暴露", "女生就该穿裙子", "女孩就该穿裙子", "穿裙子才像女生", "女生要穿裙子", "穿成这样不正经", "穿成这样不体面", "穿成这样不自爱", "女生别穿成这样出门"],
      "exclude_any": ["谁让你", "活该", "怪你自己", "不怪别人怪你", "不怪别人怪你自己", "谁让你穿成那样", "谁让你穿这么露", "出事别怪别人", "被骚扰也怪你自己", "被侵犯也是你自己问题", "被骚扰", "被侵犯", "被猥亵", "被强奸"],
      "labels": ["穿着规训", "外貌/身体规训"],
      "severity_default": "high",
      "confidence_default": "medium",
      "surface_meaning_template": "说话者在评论女性穿着是否符合其认为的安全或体面标准。",
      "hidden_structure_template": "这类表达常把风险管理和道德责任更多压在女性身上，而不是审视实施骚扰或评价的人。",
      "impact_template": "可能强化羞耻、身体监控和受害者自责。",
      "gentle_response": "安全和尊重不应该建立在女性必须自我约束穿着上。",
      "boundary_response": "请不要把他人的行为责任转移到我的穿着上。",
      "question_response": "为什么总是要求女性先限制自己，而不是要求别人守边界？",
      "notes": "更偏“穿着是否体面/得体/像不像女生”的规训；一旦出现明确责备受害者，更应交给 R033。",
      "priority": 82,
      "contexts": []
    },
    {
      "rule_id": "R020",
      "name": "女生就别喝酒/别晚归",
      "must_include_any": ["女生", "女孩", "女人"],
      "must_include_any_2": ["别喝酒", "别去喝酒", "别晚归", "别在外面待太晚", "晚上别乱跑", "女生晚上别自己回家", "女孩别去夜店", "女生别老往外跑", "女生晚上少出门", "不检点", "女生别喝那么多", "女生晚上别老在外面晃", "晚上别在外面玩那么晚", "女生别混夜场"],
      "exclude_any": ["谁让你", "活该", "怪你自己", "不怪别人怪你", "出事别怪别人", "谁让你晚上还在外面", "被骚扰也怪你自己", "被骚扰", "被侵犯", "别一个人旅行", "不适合做这个职业", "别去跑长途", "别一个人去那种地方"],
      "labels": ["行动自由规训", "夜间行动限制"],
      "severity_default": "medium",
      "confidence_default": "medium",
      "surface_meaning_template": "说话者在对女性行动自由提出限制。",
      "hidden_structure_template": "这类表达可能把公共空间的不安全转化为女性自我约束的义务。",
      "impact_template": "可能让女性承担额外的行动限制和道德责任。",
      "gentle_response": "我理解安全顾虑，但安全责任不应该只由女性承担。",
      "boundary_response": "我不接受用性别来限制我的基本行动自由。",
      "question_response": "为什么面对风险时，首先被要求收缩的是女性的自由？",
      "notes": "更偏“晚归、喝酒、夜生活、晚上出门”的限制；如果是在说女性不该独自去某地或某职业不适合女性，更应交给 R043；如果把伤害责任推回受害者，更应交给 R033。",
      "priority": 81,
      "contexts": []
    },
    {
      "rule_id": "R021",
      "name": "女生说话别这么冲",
      "must_include_any": ["女生", "女孩", "女人"],
      "must_include_any_2": ["别这么冲", "别这么直接", "别顶嘴", "说话柔一点","别这么凶","要淑女","要礼貌"],
      "exclude_any": [],
      "labels": ["权力/服从结构", "表达规训"],
      "severity_default": "medium",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在要求女性以更柔和、更低冲突的方式表达。",
      "hidden_structure_template": "这句话可能把女性的表达边界压缩到“可接受的温和”范围内，从而降低其发声力量。",
      "impact_template": "可能让女性在必要的拒绝、反驳或谈判时不敢直接表达。",
      "gentle_response": "我可以保持尊重，但也需要直接把意思说清楚。",
      "boundary_response": "我不认为女性表达直接就天然有问题。",
      "question_response": "为什么直接表达在女性身上更容易被视为冒犯？",
      "notes": "与“凶、顶嘴、礼貌、态度”共现更强。",
      "priority": 80,
      "contexts": []
    },
    {
      "rule_id": "R022",
      "name": "嫁得好比干得好重要",
      "must_include_any": ["嫁得好", "找个好老公", "婚姻比事业重要", "找个男人就好了", "找个男人就行了", "女人该结婚", "女生该结婚", "女孩该结婚", "女人就该结婚"],
      "must_include_any_2": [],
      "exclude_any": [],
      "labels": ["家庭角色期待", "经济依附期待"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把婚姻当作女性最优的人生资源配置方式。",
      "hidden_structure_template": "这句话把女性获得资源的路径更多设定为婚姻，而不是个人能力、职业和自主选择。",
      "impact_template": "可能弱化女性对长期独立和自我建设的投入。",
      "gentle_response": "关系可以重要，但我也很重视自己建立能力和选择权。",
      "boundary_response": "我不接受把婚姻当成女性的主要上升路径。",
      "question_response": "为什么女性的人生成功更容易被定义成“嫁得好”？",
      "notes": "常见于长辈或婚恋话语。",
      "priority": 79,
      "contexts": []
    },
    {
      "rule_id": "R023",
      "name": "女人就是麻烦/事多",
      "must_include_any": ["女人就是", "女生就是", "女的都"],
      "must_include_any_2": ["麻烦", "事多", "矫情", "难搞", "爱作"],
      "exclude_any": [],
      "labels": ["群体贬低", "情绪污名化"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在用概括性语言贬低女性群体。",
      "hidden_structure_template": "这句话把个体差异抹平，用贬低性格词汇给整个女性群体贴标签。",
      "impact_template": "会强化公开的厌女表达和群体污名。",
      "gentle_response": "用这种方式概括整个群体并不准确。",
      "boundary_response": "我不接受对女性群体的笼统贬低。",
      "question_response": "为什么把个体经验直接上升成对整个女性群体的评价？",
      "notes": "这类泛化语句通常可直接高置信度判定。",
      "priority": 78,
      "contexts": []
    },
    {
      "rule_id": "R024",
      "name": "生孩子是女人的责任",
      "must_include_any": ["女人", "女生", "女孩", "老婆", "妻子"],
      "must_include_any_2": ["生孩子是责任", "总要生孩子", "不生不完整", "要给家里传宗接代"],
      "exclude_any": [],
      "labels": ["生育规训", "家庭角色期待"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把生育设定为女性应尽义务。",
      "hidden_structure_template": "这句话把女性身体和人生价值绑定在生育功能上，弱化其自主决定权。",
      "impact_template": "可能制造强烈的生育压力和身份羞耻。",
      "gentle_response": "生育应该是自主选择，而不是默认责任。",
      "boundary_response": "我不接受把女性价值建立在必须生育上。",
      "question_response": "为什么女性的完整性要通过生育来证明？",
      "notes": "与家庭、传宗接代、年龄语境高度相关。",
      "priority": 77,
      "contexts": []
    },
    {
      "rule_id": "R025",
      "name": "当领导就别那么有情绪",
      "must_include_any": ["情绪", "不理性", "太感性"],
      "must_include_any_2": ["领导", "管理", "决策", "女生"],
      "exclude_any": [],
      "labels": ["情绪压制", "职业/能力偏见"],
      "severity_default": "medium",
      "confidence_default": "medium",
      "surface_meaning_template": "说话者在质疑某人的职业判断是否受到情绪影响。",
      "hidden_structure_template": "在女性领导语境中，这类说法常把女性的情绪可见性等同于能力不足，而忽视男性情绪的常态化。",
      "impact_template": "可能让女性在领导场域中承受更严苛的理性标准。",
      "gentle_response": "表达情绪和做出专业判断并不是对立的。",
      "boundary_response": "请不要把女性的表达方式直接等同于能力问题。",
      "question_response": "为什么类似表达在男性领导身上不一定会被同样解释？",
      "notes": "必须结合管理/领导语境才更稳。",
      "priority": 76,
      "contexts": []
    },
    {
      "rule_id": "R026",
      "name": "你一个女生怎么敢这样",
      "must_include_any": ["你一个女生", "一个女孩", "作为女人"],
      "must_include_any_2": ["怎么敢", "怎么能", "居然敢", "还敢"],
      "exclude_any": [],
      "labels": ["权力/服从结构", "越界惩罚"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把某个行为定义为女性不应做出的越界举动。",
      "hidden_structure_template": "这句话直白地表明：同样的行为在女性身上更容易被视为越界、不守本分或不知分寸。",
      "impact_template": "可能通过羞辱来惩罚女性的主体性、反抗或竞争行为。",
      "gentle_response": "我只是正常表达和行动，并没有什么“不该”。",
      "boundary_response": "我不接受因为性别就被要求降低边界和行动空间。",
      "question_response": "为什么同样的行为放在女性身上就变成“越界”？",
      "notes": "高指向性规则。",
      "priority": 75,
      "contexts": []
    },
    {
      "rule_id": "R027",
      "name": "女孩家家",
      "must_include_any": ["女孩家家", "一个女孩", "女孩就该"],
      "must_include_any_2": [],
      "exclude_any": [],
      "labels": ["性别角色规范"],
      "severity_default": "medium",
      "confidence_default": "medium",
      "surface_meaning_template": "说话者在借女性身份对行为提出规范性要求。",
      "hidden_structure_template": "这类说法常是后续规训的开头，暗示女性需要更守规矩、更体面、更克制。",
      "impact_template": "可能把“像个女孩”变成持续的行为监督。",
      "gentle_response": "我更希望先按行为本身来讨论，而不是先按性别来要求。",
      "boundary_response": "请不要用“女孩就该怎样”来限制我。",
      "question_response": "为什么先被拿出来要求的是“女孩身份”而不是行为本身？",
      "notes": "需结合后续句子增强判定。",
      "priority": 74,
      "contexts": []
    },
    {
      "rule_id": "R028",
      "name": "女生结婚后该以家庭为主",
      "must_include_any": ["结婚后", "婚后","结婚"],
      "must_include_any_2": ["以家庭为主", "重心回归家庭", "别折腾事业了", "为了家牺牲一点"],
      "exclude_any": [],
      "labels": ["家庭角色期待", "职业/能力偏见"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在要求女性婚后重新安排人生优先级。",
      "hidden_structure_template": "这句话把婚后家庭责任主要压向女性，并默认她应主动缩减事业和自我发展。",
      "impact_template": "可能把婚姻变成女性职业后退的制度化节点。",
      "gentle_response": "婚后如何安排应该由双方共同协商，不该默认只由女性让步。",
      "boundary_response": "我不接受婚后就必须牺牲女性发展的前提设定。",
      "question_response": "为什么婚后主要被要求调整的是女性，而不是双方共同调整？",
      "notes": "婚姻转换节点高频。",
      "priority": 73,
      "contexts": []
    },
    {
      "rule_id": "R029",
      "name": "女生别抛头露面",
      "must_include_any": ["女生", "女人", "女孩"],
      "must_include_any_2": ["别抛头露面", "低调一点", "别太出风头", "别总在外面"],
      "exclude_any": [],
      "labels": ["公共空间规训", "权力/服从结构"],
      "severity_default": "high",
      "confidence_default": "medium",
      "surface_meaning_template": "说话者在限制女性的可见性、表达或社会参与。",
      "hidden_structure_template": "这类表达默认女性更应留在低可见、低冲突的位置，而非占据公共空间和话语空间。",
      "impact_template": "可能压缩女性参与、表达和争取资源的机会。",
      "gentle_response": "公共表达和参与本来就是每个人的权利。",
      "boundary_response": "我不接受把女性限制在更低可见的位置上。",
      "question_response": "为什么女性的公开表达更容易被视为“出风头”？",
      "notes": "适合结合工作、社交媒体、公开发言场景。",
      "priority": 72,
      "contexts": []
    },
    {
      "rule_id": "R031",
      "name": "剩女/贬值叙事",
      "must_include_any": ["女人", "女生", "女孩", "女性", "剩女", "大龄女", "三十多的女的", "年纪大的女人"],
      "must_include_any_2": ["贬值", "不值钱", "掉价", "剩下了", "年纪大了没人要", "过了三十就不值钱", "大龄剩女", "老剩女", "越老越掉价", "年纪一大就贬值", "大龄就很难嫁", "三十多就难嫁了","不结婚来不及","早点结婚"],
      "exclude_any": ["资产贬值", "货币贬值", "房子贬值", "股票贬值", "车子贬值"],
      "labels": ["婚育时钟规训", "婚恋市场化评价", "年龄羞辱"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在用市场化语言评价女性的年龄与婚恋价值。",
      "hidden_structure_template": "这类说法把女性当作会随年龄折损的婚恋商品，而不是拥有独立节奏和主体价值的人。",
      "impact_template": "可能强化年龄焦虑、婚恋恐慌和女性自我物化。",
      "gentle_response": "我不认同用“贬值”这种商品语言来评价女性的人生。",
      "boundary_response": "请不要把女性当成会随年龄折损的婚恋商品。",
      "question_response": "为什么女性的年龄更容易被转换成“掉价”或“贬值”的说法？",
      "notes": "和年龄、婚恋、剩女、值不值钱等表达一起出现时更稳。",
      "priority": 71,
      "contexts": []
    },
    {
      "rule_id": "R032",
      "name": "二手/掉价/不值钱",
      "must_include_any": ["女生", "女孩", "女人", "女性"],
      "must_include_any_2": ["二手", "掉价", "不值钱", "贬值", "不干净了", "像二手货", "二手女人", "不清白了", "有过男人就掉价", "谈过就不值钱","赔钱"],
      "exclude_any": ["二手车", "二手房", "二手平台", "商品掉价", "数码产品"],
      "labels": ["婚恋市场化评价", "性经验羞辱", "双重标准"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在用商品折旧、转手等隐喻评价女性的关系经历或性经验。",
      "hidden_structure_template": "这类说法把女性主体转化为可被消费、流通和折价的对象，并常伴随对男性更宽松的双重标准。",
      "impact_template": "可能制造羞耻感，强化对女性关系经历与身体的控制。",
      "gentle_response": "关系经历不会把一个人变成“二手”或“掉价”。",
      "boundary_response": "请不要用商品化语言来羞辱女性的关系经历和身体。",
      "question_response": "为什么同样的经历在男性身上常被淡化，在女性身上却被说成“掉价”？",
      "notes": "适合与恋爱史、主动、纯洁、干净等语境联动。",
      "priority": 70,
      "contexts": []
    },
    {
      "rule_id": "R033",
      "name": "被骚扰/被侵犯是自己问题",
      "must_include_any": ["骚扰", "侵犯", "出事", "被占便宜", "被猥亵", "被强奸", "被欺负", "被尾随"],
      "must_include_any_2": ["谁让你", "活该", "你自己不注意", "你自己导致的", "也是你自己问题", "怪你自己", "那也是你自找的", "谁叫你这样", "出事也怪你", "不怪别人怪你自己", "出事别怪别人", "被骚扰也怪你自己", "被侵犯也是你自己问题", "谁让你晚上还在外面", "谁让你一个人去"],
      "exclude_any": ["案例分析", "法律科普", "新闻标题", "不是受害者的错", "不能怪受害者"],
      "labels": ["责备受害者", "受害者归因风险"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把骚扰或侵犯的责任部分转移到受害者身上。",
      "hidden_structure_template": "这类表达通过检讨女性的穿着、行为或选择，模糊施害者责任，要求女性为他人越界承担后果。",
      "impact_template": "可能加剧受害者羞耻、自责和沉默，削弱对施害行为的追责。",
      "gentle_response": "责任应该放在越界的人身上，而不是受害者身上。",
      "boundary_response": "我不接受把骚扰或侵犯的责任转移到受害者身上。",
      "question_response": "为什么发生伤害时，先被追问和检讨的总是受害者而不是施害者？",
      "notes": "更偏“把伤害责任推回受害者”；如果只是要求女性穿着得体、不露太多，更应交给 R019；如果只是限制晚归、喝酒或一个人去某地，但没有明确责怪受害者，更应交给 R020 / R043。",
      "priority": 69,
      "contexts": []
    },
    {
      "rule_id": "R034",
      "name": "月经/怀孕就别矫情",
      "must_include_any": ["例假", "月经", "大姨妈", "怀孕", "孕妇", "经期"],
      "must_include_any_2": ["矫情", "情绪化", "作", "激素问题", "别拿这个说事", "别这么玻璃心", "是不是来大姨妈了", "是不是经期到了", "是不是怀孕了才这样", "来例假就别闹了"],
      "exclude_any": ["生理期科普", "经期科普", "医学上", "医生说", "健康教育"],
      "labels": ["生理污名化", "情绪压制", "认知贬低"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在用女性生理状态否定其表达、感受或判断。",
      "hidden_structure_template": "这类说法把女性正常的身体经验病理化、问题化，再借此削弱她的表达正当性与判断能力。",
      "impact_template": "可能让女性在生理或孕期不适中更难表达需求，也更容易被视为“不理性”。",
      "gentle_response": "生理状态不应该成为否定我表达和需求的理由。",
      "boundary_response": "请不要用月经或怀孕来贬低女性的感受和判断。",
      "question_response": "为什么一旦女性表达不适或立场，就容易被归因为“激素”或“情绪问题”？",
      "notes": "与情绪、矫情、激素、作、别上纲上线等表达联动更强。",
      "priority": 68,
      "contexts": []
    },
    {
      "rule_id": "R035",
      "name": "女人天生不理性",
      "must_include_any": ["女人", "女生", "女性", "女孩"],
      "must_include_any_2": ["天生感性", "不理性", "做决定靠情绪", "脑子不清楚", "理智不了", "就是感情用事", "女人就是不理智", "女生本来就感性", "女的做事靠感觉", "女人天生不适合做决定", "什么都不懂"],
      "exclude_any": ["反驳这种偏见", "并不是女人都", "不能说女人都", "刻板印象"],
      "labels": ["职业/能力偏见", "认知贬低", "父权合理化"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把女性的不理性或感情用事当作天然特质。",
      "hidden_structure_template": "这类说法把女性的判断力和权威资格天然化地压低，为决策权更多掌握在男性手中提供正当性。",
      "impact_template": "可能削弱女性在工作、公共讨论和关系决策中的可信度。",
      "gentle_response": "判断力不能直接按性别概括，每个人都需要看具体情境。",
      "boundary_response": "我不接受把女性天然定义成更不理性或更不适合做决定。",
      "question_response": "为什么男性的情绪常被当作个体问题，而女性的情绪更容易被说成群体天性？",
      "notes": "和决策、理性、判断、情绪化、感性等语境联动较强。",
      "priority": 67,
      "contexts": []
    },
    {
      "rule_id": "R036",
      "name": "男主外女主内本来就合理",
      "must_include_any": ["男主外女主内", "男人负责赚钱", "女人负责顾家", "男人在外面", "女人在家里"],
      "must_include_any_2": ["本来就这样", "天经地义", "自然规律", "自古如此", "本来就合理", "很正常", "自古以来都这样", "老祖宗就是这么定的", "本来就该这么分工", "这才是正常家庭"],
      "exclude_any": ["反对男主外女主内", "批评男主外女主内", "不是天经地义", "并不合理"],
      "labels": ["家庭角色期待", "父权合理化", "经济依附期待"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把性别分工描述为自然、传统或不可质疑的安排。",
      "hidden_structure_template": "这类表达把历史形成的父权分工包装成自然规律，淡化了其对女性自由、收入与时间分配的限制。",
      "impact_template": "可能巩固女性承担照护劳动、男性掌握资源和决定权的不对称结构。",
      "gentle_response": "家庭分工应该由双方协商，而不是按性别天然分配。",
      "boundary_response": "我不接受把父权分工包装成所谓“自然规律”或“天经地义”。",
      "question_response": "为什么这些所谓“自然分工”最后往往都是女性更多让步、男性更多掌握资源？",
      "notes": "适合与传统、顾家、赚钱养家、在家带孩子等表达一起判断。",
      "priority": 66,
      "contexts": []
    },
    {
      "rule_id": "R037",
      "name": "女人不生孩子有什么用",
      "must_include_any": ["女人", "女生", "女性", "老婆", "妻子"],
      "must_include_any_2": ["不生孩子有什么用", "不当妈有什么用", "女人就是要生孩子", "生不了就没价值", "不生就白当女人", "不生就是不完整", "不生孩子算什么女人", "女人总得生一个", "不当妈人生不完整", "女人的用处就是生孩子"],
      "exclude_any": ["女性价值不该建立在生育上", "不生也有价值", "不能这样要求女性"],
      "labels": ["生育规训", "生理污名化", "父权合理化"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把女性的人生价值强行绑定到生育功能上。",
      "hidden_structure_template": "这类表达把女性的身体和身份定义为生育工具，使其完整性与价值必须经由生育来证明。",
      "impact_template": "可能制造强烈的生育焦虑、羞耻感和身份压迫。",
      "gentle_response": "生不生孩子都不决定一个女性有没有价值。",
      "boundary_response": "我不接受把女性价值建立在必须生育上。",
      "question_response": "为什么女性的存在意义要被压缩成生育功能，而不是她本人的选择和生活？",
      "notes": "与完整、不完整、价值、传宗接代等表达相关时更强。",
      "priority": 65,
      "contexts": []
    },
    {
      "rule_id": "R038",
      "name": "女生出门就该化妆/精致",
      "must_include_any": ["女生", "女人", "女孩", "女性"],
      "must_include_any_2": ["就该化妆", "必须精致", "女人就要精致一点", "出门化个妆", "女生要懂打扮", "不化妆不像样", "女生出门得收拾一下", "女孩见人要精致点", "出门素颜不合适", "女的就得打扮得体"],
      "exclude_any": ["个人选择", "自己喜欢化妆", "我喜欢化妆", "审美自由", "女生要穿裙子", "女孩就该穿裙子", "穿裙子才像女生"],
      "labels": ["服美役规训", "外貌/身体规训", "物化"],
      "severity_default": "medium",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把女性维持特定外表状态当成默认义务。",
      "hidden_structure_template": "这类表达把女性时间、金钱和注意力更多绑定到可被观看和评价的外貌劳动上。",
      "impact_template": "可能强化服美役压力，让女性把“被看起来合格”误当作日常责任。",
      "gentle_response": "外表可以是个人选择，但不该成为女性的默认义务。",
      "boundary_response": "我不接受把化妆、精致和女性价值或体面直接绑定。",
      "question_response": "为什么这些外貌劳动更常被视为女性必须完成的日常责任？",
      "notes": "更偏“化妆、精致、收拾自己、出门得像样”的外貌劳动；如果重点是穿得露不露、该不该穿裙子，更应交给 R019。",
      "priority": 64,
      "contexts": []
    },
    {
      "rule_id": "R039",
      "name": "太优秀男人不敢要",
      "must_include_any": ["女生", "女人", "女性", "女强人", "优秀女人", "太能干的女人"],
      "must_include_any_2": ["太优秀男人不敢要", "太强没人敢娶", "太厉害男人会怕", "事业太强婚姻不会好", "太独立不好找对象", "优秀的女人难嫁", "女人太能干男人受不了", "太会赚钱男人有压力", "条件太好反而没人要", "太强势男人不会喜欢", "赚太多男人受不了", "职位太高男人有压力", "学历太高不好找对象"],
      "exclude_any": ["这话不对", "并不是太优秀没人要", "不该这样说女性"],
      "labels": ["婚恋惩罚叙事", "职业/能力偏见", "经济依附期待"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在暗示女性一旦太优秀、太独立，就会在婚恋里受到惩罚。",
      "hidden_structure_template": "这类表达把女性成就和亲密关系人为对立起来，要求女性为了被爱而主动缩小自己。",
      "impact_template": "可能让女性在发展能力、收入和话语权时产生内疚或自我收缩。",
      "gentle_response": "优秀和被爱并不是对立的，也不该要求女性为了关系而主动缩小自己。",
      "boundary_response": "我不接受用“没人敢要”来惩罚女性的独立、优秀和成就。",
      "question_response": "为什么女性越优秀越容易被说成“没人敢要”，而男性越优秀却更常被视为加分？",
      "notes": "和太独立、太厉害、太强、婚姻不好等说法一起出现时较强。",
      "priority": 63,
      "contexts": []
    },
    {
      "rule_id": "R040",
      "name": "女孩还是要单纯",
      "must_include_any": ["女生", "女孩", "女人", "女性"],
      "must_include_any_2": ["要干净一点", "不干净", "不纯洁", "太脏了", "名声会坏", "女孩还是要洁身自好", "女孩要自爱", "别把自己搞脏了", "谈多了就不干净了", "女的还是要检点","不单纯", "要单纯"],
      "exclude_any": ["不要用干净评价女性", "不该用纯洁标准", "反对贞洁观"],
      "labels": ["性经验羞辱", "性/亲密关系控制", "双重标准"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在用“干净/不干净”一类道德化语言评价女性的性经验或亲密关系经历。",
      "hidden_structure_template": "这类表达把女性身体和欲望置于更严厉的道德审查之下，通过纯洁叙事维持对女性亲密关系的控制。",
      "impact_template": "可能制造羞耻感、自我审查和对女性更严格的亲密关系标准。",
      "gentle_response": "请不要用“干净”或“纯洁”这种标准来约束和评价女性。",
      "boundary_response": "我不接受把女性的身体和关系经历放进带有羞辱意味的纯洁审查里。",
      "question_response": "为什么“干净”这种标准更常被拿来要求女性，而不是平等地要求所有人？",
      "notes": "与矜持、名声、纯洁、二手、洁身自好等表达联动时更稳。",
      "priority": 62,
      "contexts": []
    },
    {
      "rule_id": "R041",
      "name": "女生老了就不好看/没价值",
      "must_include_any": ["女生", "女孩", "女人", "女性"],
      "must_include_any_2": ["老了就不好看", "年纪大了就不好看", "一老就不值钱", "女人老得快", "过了年纪就没魅力", "女生老了就没人看"],
      "exclude_any": ["反对年龄羞辱", "不该这样评价女性年龄", "年龄不该定义价值"],
      "labels": ["外貌年龄羞辱", "外貌/身体评价", "婚恋市场化评价"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把女性的年龄增长直接等同于外貌下滑或价值流失。",
      "hidden_structure_template": "这类说法把女性价值压缩成“年轻、可看、可选择”的状态，让年龄成为更严厉地落在女性身上的倒计时。",
      "impact_template": "可能强化年龄焦虑、外貌压力和对女性自我价值的持续贬低。",
      "gentle_response": "年龄变化不应该被拿来贬低一个女性的价值和魅力。",
      "boundary_response": "我不接受把女性年龄直接等同于贬值或失去吸引力。",
      "question_response": "为什么年龄增长在女性身上更常被说成“掉价”，而不是自然的人生变化？",
      "notes": "和年纪、外貌、魅力、值不值钱、有没有人看等表达联动更强。",
      "priority": 61,
      "contexts": []
    },
    {
      "rule_id": "R042",
      "name": "女生就是事多/难带/麻烦",
      "must_include_any": ["女生就是", "女人就是", "女孩就是", "女的就是"],
      "must_include_any_2": ["事多", "难带", "麻烦", "难搞", "不好合作", "情绪多", "带不动"],
      "exclude_any": ["不能这样概括女性", "不该这样说女生", "反对这种偏见"],
      "labels": ["群体贬低", "情绪污名化", "职业/能力偏见"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在用概括性语言把女性群体描述成更麻烦、更难合作或更难相处。",
      "hidden_structure_template": "这类表达把个体差异抹平，再用带有负面管理意味的词给女性整体贴标签。",
      "impact_template": "可能让女性在合作、职场或关系中更容易被先入为主地贬低和排斥。",
      "gentle_response": "用这种方式概括整个群体并不准确，也不公平。",
      "boundary_response": "我不接受把女性整体说成“麻烦”或“难带”。",
      "question_response": "为什么个体经验会被直接上升成对整个女性群体的负面结论？",
      "notes": "在职场和关系语境里都常见，通常可高置信度判定。",
      "priority": 60,
      "contexts": []
    },
    {
      "rule_id": "R043",
      "name": "女生不该一个人去/做这些事",
      "must_include_any": ["女生", "女孩", "女人", "女的"],
      "must_include_any_2": ["不该一个人去", "别一个人去", "不适合一个人去", "别去那种地方", "不适合做这个职业", "别去跑长途", "别走夜路", "别一个人旅行", "不适合单独出差", "女生别自己去", "别自己去外地", "别一个人去那种地方", "女生别单独去", "女生不适合跑夜班"],
      "exclude_any": ["安全建议而已", "只是提醒安全", "不是因为性别", "男女都一样", "谁让你", "活该", "怪你自己", "不怪别人怪你", "出事别怪别人", "谁让你一个人去", "谁让你晚上还在外面", "别喝酒", "别晚归", "女孩别去夜店", "被骚扰", "被侵犯"],
      "labels": ["公共空间限制", "独立行动规训"],
      "severity_default": "high",
      "confidence_default": "medium",
      "surface_meaning_template": "说话者在用性别来限制女性进入某些空间、职业或行动方式。",
      "hidden_structure_template": "这类表达把公共空间和自主行动默认为更适合男性，让女性先承担收缩自由的成本。",
      "impact_template": "可能压缩女性的职业选择、空间使用和独立行动的正当性。",
      "gentle_response": "安全顾虑可以讨论，但不应该直接因为性别就限制女性的行动和选择。",
      "boundary_response": "我不接受因为性别就被默认限制能去哪里、能做什么。",
      "question_response": "为什么面对风险时，先被要求收缩的是女性，而不是改变环境和规则？",
      "notes": "更偏“女性不该独自去某地、跑远路、做某类工作”的空间与行动限制；如果只是限制晚归、喝酒、夜生活，更应交给 R020；如果是在责怪受害者，更应交给 R033。",
      "priority": 59,
      "contexts": []
    },
    {
      "rule_id": "R044",
      "name": "当妈后就该以孩子为先",
      "must_include_any": ["当妈了", "有孩子了", "做妈妈了", "当母亲了", "孩子都有了"],
      "must_include_any_2": ["孩子最重要", "别只想着自己", "先顾孩子", "还折腾什么事业", "别打扮了", "重心放孩子身上"],
      "exclude_any": ["母亲也需要自己的人生", "不该这样要求妈妈", "妈妈也可以有自己的生活"],
      "labels": ["母职优先", "母职规训", "家庭角色期待"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在要求女性成为母亲后，把孩子和照护责任放到压倒性的优先位置。",
      "hidden_structure_template": "这类说法把母亲身份扩大成女性唯一的正当身份，让她的事业、外貌、兴趣和个人空间被视为次要甚至不合适。",
      "impact_template": "可能让母亲在照护之外的目标都被看成自私或不负责任，进一步压缩个人空间。",
      "gentle_response": "有孩子以后当然会多考虑孩子，但这不代表母亲就不能有自己的生活和目标。",
      "boundary_response": "我不接受把母亲身份变成要求女性放弃自我和发展的理由。",
      "question_response": "为什么一旦成为母亲，最先被要求放弃个人空间和目标的总是女性？",
      "notes": "与事业、打扮、出门、孩子最重要等表达联动更强。",
      "priority": 58,
      "contexts": []
    },
    {
      "rule_id": "R045",
      "name": "她就该配合我/别拖我后腿",
      "must_include_any": ["她就该", "老婆就该", "女友就该", "对象就该", "女人就该配合"],
      "must_include_any_2": ["配合我", "别拖我后腿", "别影响我", "围着我转", "跟着我安排", "以我为主"],
      "exclude_any": ["关系应该平等", "不该只让她配合", "应该一起协商"],
      "labels": ["关系中的资源不对称", "权力/服从结构", "资源控制"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在默认女性伴侣应围绕自己的节奏、目标和安排来行动。",
      "hidden_structure_template": "这类表达把关系中的协商变成单向配合，默认男性目标更重要、女性让步更正常。",
      "impact_template": "可能使女性伴侣持续承担时间、机会和情绪上的让步，关系逐渐失衡。",
      "gentle_response": "关系里的支持应该是双向的，不应该默认只由一方长期配合。",
      "boundary_response": "我不接受把伴侣关系变成单向配合和默认让步。",
      "question_response": "为什么默认是她来配合你的节奏，而不是双方一起协商？",
      "notes": "适合与事业、安排、迁就、跟随、让步等表达一起判断。",
      "priority": 57,
      "contexts": []
    },
    {
      "rule_id": "R046",
      "name": "主见太多/太会说不好嫁",
      "must_include_any": ["女生", "女孩", "女人", "女性"],
      "must_include_any_2": ["主见太多不好嫁", "太会说不好嫁", "太有想法不好找对象", "太有主见男人不喜欢", "嘴太厉害不好嫁", "太会表达男人受不了","有主见不好", "太有主意不好嫁", "太有想法男人不喜欢"],
      "exclude_any": ["不该这样说女性", "主见不是问题", "反对这种婚恋惩罚"],
      "labels": ["婚恋惩罚叙事", "表达规训"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把女性的主见、表达能力或思想独立解释成婚恋中的减分项。",
      "hidden_structure_template": "这类表达是在要求女性为了更容易被接受或被选择，而主动降低自己的表达、判断和存在感。",
      "impact_template": "可能让女性把有主见和被喜欢对立起来，从而削弱表达与决策的主体性。",
      "gentle_response": "有主见和会表达并不是问题，也不该被当成女性婚恋中的减分项。",
      "boundary_response": "我不接受用“不好嫁”来惩罚女性的主见、表达和独立性。",
      "question_response": "为什么女性一旦更有主见和表达能力，就更容易被说成“不好嫁”？",
      "notes": "更偏“有主见会不好嫁/男人不喜欢”的婚恋惩罚；如果只是要求女性不要有主见，更应交给 R006。",
      "priority": 56,
      "contexts": []
    },
    {
      "rule_id": "R047",
      "name": "把女性和爱花钱/消费主义绑定",
      "must_include_any": ["女生", "女孩", "女人", "女性", "女的"],
      "must_include_any_2": ["爱花钱", "花钱多", "花钱厉害", "喜欢花钱", "拜金", "只会买买买", "消费欲强", "乱花钱","收礼物","爱收礼物"],
      "exclude_any": ["不是女生都爱花钱", "不该这样概括女性", "反对把女性和消费主义绑定"],
      "labels": ["消费污名化", "群体贬低", "认知贬低"],
      "severity_default": "medium",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把女性概括成更爱消费、缺乏节制或天然更拜金的一类人。",
      "hidden_structure_template": "这类表达把个体消费习惯上升为对女性整体的刻板印象，暗示女性更冲动、更物质、更不值得信任。",
      "impact_template": "可能让女性在金钱、消费和价值判断上更容易被污名化，也会掩盖真实的个体差异和消费结构。",
      "gentle_response": "消费习惯还是看个人，不能直接把整个女性群体概括成“爱花钱”。",
      "boundary_response": "我不接受把女性整体和拜金、乱花钱这类标签直接绑定。",
      "question_response": "为什么个体的消费行为会被直接上升成对整个女性群体的刻板印象？",
      "notes": "适合与爱花钱、拜金、买买买、乱花钱等表达联动判断。",
      "priority": 55,
      "contexts": []
    },
    {
      "rule_id": "R048",
      "name": "女生太软弱/爱哭",
      "must_include_any": ["女生", "女孩", "女人", "女性", "女的"],
      "must_include_any_2": ["太软弱", "太脆弱", "爱哭", "动不动就哭", "一说就哭", "胆子小", "经不起事"],
      "exclude_any": ["不是软弱", "不该这样说女性", "反对把女性说成软弱", "不是爱哭就是软弱"],
      "labels": ["性别角色规范", "认知贬低", "群体贬低"],
      "severity_default": "medium",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把软弱、脆弱或爱哭当作女性更典型的性格特征。",
      "hidden_structure_template": "这类说法会把女性限定成更脆弱、更不能承压的一类人，让勇敢、稳定和扛事被默认成更偏男性的品质。",
      "impact_template": "可能削弱女性在冲突、决策和承担责任场景中的可信度，也会压缩女性表达复杂情绪的空间。",
      "gentle_response": "情绪表达和承受能力不能只按性别来概括，每个人的反应都不一样。",
      "boundary_response": "我不接受把女性整体说成更软弱、爱哭或更扛不住事。",
      "question_response": "为什么这些性格评价总更容易被拿来概括女性，而不是当作个体差异来看？",
      "notes": "适合与软弱、爱哭、胆小、经不起事等表达联动判断。",
      "priority": 54,
      "contexts": []
    },
    {
      "rule_id": "R049",
      "name": "女生要少吃/吃得少",
      "must_include_any": ["女生", "女孩", "女人", "女性"],
      "must_include_any_2": ["女生要吃得少", "女孩要吃得少", "女生吃得少", "女孩吃得少", "女生要少吃点", "女孩要少吃点", "女生就该少吃点", "女人要少吃点", "女生别吃那么多", "女孩别吃那么多", "女生饭量要小一点", "女孩饭量要小一点", "女孩子要控制饭量", "女人饭量别太大", "女生饭量别那么大", "吃太多不像女生", "吃相不像女生", "女生吃饭要斯文一点", "女生吃饭别那么猛", "女孩子饭量别太大", "女孩吃饭别狼吞虎咽", "女生别吃太快", "女孩别吃太快", "女生吃饭要文雅点", "女人吃饭斯文点"],
      "exclude_any": ["按时吃饭", "正常吃饭", "营养建议", "健康饮食", "医生建议", "多吃点身体才好", "食量小是天生的", "饭量本来就小"],
      "labels": ["饮食规训", "身体规训"],
      "severity_default": "medium",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把女性的进食量、饭量或饮食习惯纳入性别化要求。",
      "hidden_structure_template": "这类表达不是单纯谈饮食，而是在要求女性通过克制食欲和饭量来符合被期待的身体形象。",
      "impact_template": "可能加重女性的饭量羞耻、身体焦虑和对自我饮食的持续监控。",
      "gentle_response": "吃多少应该看身体需要，而不是看性别期待。",
      "boundary_response": "我不接受用“女生就该少吃”来规训女性的身体和饭量。",
      "question_response": "为什么女性连吃多少都更容易被拿来要求和评价？",
      "notes": "更偏“饭量、吃相、吃太多不像女生、女生该少吃点”的饮食规训，不主打婚恋惩罚，也不主打单纯变美。",
      "priority": 53,
      "contexts": []
    },
    {
      "rule_id": "R050",
      "name": "把女性关系说成天然雌竞",
      "must_include_any": ["女生", "女孩", "女人", "女的", "女的之间", "女人之间"],
      "must_include_any_2": ["雌竞", "爱雌竞", "就会雌竞", "勾心斗角", "互相嫉妒", "互相攀比", "争风吃醋", "女人何苦为难女人", "女人之间都是宫斗", "女的就爱抢男人", "女的最爱互撕", "女生就是喜欢比来比去", "女人之间就会斗来斗去", "女生最会搞小团体", "女生最爱抱团排挤", "女人之间最爱玩心眼", "女的就是一股茶味", "女生都很茶", "绿茶婊", "白莲花", "雌竞脑"],
      "exclude_any": ["不是雌竞", "别总说雌竞", "反对把女性关系说成雌竞", "不是所有女生都这样", "批评雌竞标签", "别把女生都说成雌竞", "不该用雌竞概括女性", "这种说法很厌女", "这是在污名化女性关系"],
      "labels": ["关系污名化", "群体贬低", "厌女叙事"],
      "severity_default": "medium",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把女性之间的关系概括成天然互害、争斗或围绕男性竞争。",
      "hidden_structure_template": "这类表达把女性关系扁平化为“雌竞”，默认女性更难建立平等合作，也把女性行动不断拉回男性视角。",
      "impact_template": "可能弱化女性之间的合作与互助正当性，也会把复杂处境偷换成对女性群体本身的污名。",
      "gentle_response": "人与人之间会有竞争，但没必要把女性关系直接概括成“雌竞”。",
      "boundary_response": "我不接受把女性之间的关系天然说成互害、抢夺或宫斗。",
      "question_response": "为什么一到女性之间的张力，就更容易被说成“雌竞”，而不是普通的人际冲突或竞争？",
      "notes": "更偏“把女性关系整体描述成互害、宫斗、争男人”的厌女叙事，不主打单个恋爱冲突。",
      "priority": 52,
      "contexts": []
    },
    {
      "rule_id": "R051",
      "name": "生女孩不好/女儿不如儿子",
      "must_include_any": ["女孩", "女儿", "闺女", "生女孩", "生女儿", "生女生"],
      "must_include_any_2": ["不好", "不如儿子", "还是儿子好", "没用", "赔钱", "不值钱", "白养", "没有儿子不行", "生儿子才行", "女儿就是别人家的人", "生女儿没福气", "生个女儿有什么用", "女孩终究靠不住", "没儿子不算圆满", "闺女迟早是别人家的", "断香火","香火断了", "没男丁", "招弟", "来弟", "盼儿子", "传宗接代必须靠儿子", "没儿子抬不起头", "女儿不能继后", "生女儿亏本", "养女儿没回报", "女儿不能养老", "养女儿不划算", "女儿是赔本买卖", "养闺女没用", "生女生没用", "生女孩也没用", "生女儿也没用", "不要生女孩", "不要生女儿", "别生女孩", "别生女儿"],
      "exclude_any": ["生男生女都一样", "女孩也很好", "女儿也一样重要", "反对重男轻女", "不是生女孩不好", "别再重男轻女了", "女儿也能养老", "女孩不比儿子差", "女孩一样能传承家庭"],
      "labels": ["重男轻女", "生育价值贬抑", "家庭角色期待"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把女孩或女儿的出生价值放在低于男孩的位置上。",
      "hidden_structure_template": "这类表达把子女性别直接和家族价值、资源回报或家庭脸面绑定，延续重男轻女的资源分配逻辑。",
      "impact_template": "可能让女孩从出生起就被放在更低价值的位置，也会强化家庭中的性别资源不平等。",
      "gentle_response": "孩子的价值不该由性别决定，女孩和男孩一样值得被重视。",
      "boundary_response": "我不接受把女孩的出生和存在说成更差、更没用或更不值得。",
      "question_response": "为什么孩子一旦是女孩，就更容易被放进“赔钱”“没用”“不如儿子”的评价里？",
      "notes": "更偏“生女儿不好、女儿不如儿子、儿子才有价值”的重男轻女表达，不主打一般催生。",
      "priority": 51,
      "contexts": []
    },
    {
      "rule_id": "R052",
      "name": "女孩不值得培养/读书没用",
      "must_include_any": ["女孩", "女儿", "闺女", "女生"],
      "must_include_any_2": ["读那么多书没用", "不用读太多书", "没必要供她读书", "女孩子读书没用", "培养女孩不划算", "资源该给儿子", "供女儿上学不值得", "女孩读那么高干嘛", "女儿书读多了也没用", "投资女儿不如投资儿子"],
      "exclude_any": ["女孩也该读书", "女儿也值得培养", "反对不给女孩教育", "不是女孩读书没用", "教育资源应该平等", "女孩也值得投资", "女儿读书一样有用", "不该把资源只给儿子", "培养女孩同样值得"],
      "labels": ["教育资源歧视", "重男轻女", "资源分配不平等"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把教育和培养资源更多默认投向男孩，而不是女孩。",
      "hidden_structure_template": "这类表达把女孩的成长、学习和长期发展视为低回报投资，默认资源更该优先流向男性后代。",
      "impact_template": "可能直接影响女孩获得教育、培养和家庭投入的机会，也会强化她们从小被放在次要位置。",
      "gentle_response": "教育和培养不该按性别决定，女孩同样值得被投入和支持。",
      "boundary_response": "我不接受把女孩的教育和发展说成“不值得”或“没必要”。",
      "question_response": "为什么一说到培养、读书和资源投入，女孩就更容易被当成“不划算”的对象？",
      "notes": "更偏“女孩不值得读书、培养、分配资源”的家庭与教育话语，不主打出生价值评价。",
      "priority": 50,
      "contexts": []
    },
    {
      "rule_id": "R053",
      "name": "家产/房子该留给儿子",
      "must_include_any": ["女儿", "女孩", "闺女", "儿子", "男孩"],
      "must_include_any_2": ["房子留给儿子", "家产当然给儿子", "女儿不用分那么多", "嫁出去的女儿泼出去的水", "财产该给儿子", "家里的东西要留给儿子", "女儿没资格分家产", "房产应该给儿子", "儿子才有继承权", "女儿不用争家产"],
      "exclude_any": ["女儿也有继承权", "反对不给女儿分家产", "财产分配应该平等", "不是该留给儿子", "女儿也该分家产", "房子不该只给儿子", "继承权不该只属于儿子", "女儿也有资格分财产"],
      "labels": ["继承资源不平等", "重男轻女", "资源分配不平等"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把房子、家产和继承资源默认更多留给儿子，而不是女儿。",
      "hidden_structure_template": "这类表达把家庭财产和继承权视为男性后代的天然资源，默认女儿在家庭资源分配中应被边缘化。",
      "impact_template": "可能直接造成女儿在财产、住房和家庭支持上的系统性吃亏，也会巩固家庭内部的性别等级。",
      "gentle_response": "家庭财产和支持不该按性别天然倾斜，女儿同样有平等的权利。",
      "boundary_response": "我不接受把房子、家产和继承权默认只留给儿子。",
      "question_response": "为什么一说到房子、家产和继承，女儿就更容易被排除在外，仿佛天然不该拥有同样的份额？",
      "notes": "更偏“房子、家产、继承资源优先给儿子”的家庭资源分配话语，不主打教育资源。",
      "priority": 49,
      "contexts": []
    },
    {
      "rule_id": "R054",
      "name": "照顾老人/家务主要该由女儿承担",
      "must_include_any": ["女儿", "女孩", "闺女", "女生"],
      "must_include_any_2": ["照顾老人本来就是女儿的事", "女儿就该伺候父母", "照顾爸妈主要靠女儿", "家务本来就该女儿做", "闺女就该多顾家里", "女儿得多照顾弟弟", "照顾家里应该是女孩的责任", "女儿就得多操心家里", "家里老人主要靠女儿照顾", "女孩就该会照顾人"],
      "exclude_any": ["儿女都该一起照顾", "照顾责任应该平等分担", "不是女儿一个人的责任", "反对把照护都压给女儿", "儿子女儿都该照顾父母", "家务不该只让女儿做", "照顾老人不是女儿专属义务", "不该默认女孩更会照顾人"],
      "labels": ["照护责任不平等", "家庭角色期待", "重男轻女"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把照顾老人、做家务和照护家庭的责任更多默认压给女儿。",
      "hidden_structure_template": "这类表达把照护劳动视为女性后代的天然义务，让女儿更容易被要求多承担家务、照顾和情绪劳动。",
      "impact_template": "可能让女孩和女儿在家庭里更早承担过量责任，也会让她们的时间、机会和边界持续被侵占。",
      "gentle_response": "照顾家庭不该默认只落在女儿身上，责任应该被公平分担。",
      "boundary_response": "我不接受把照护老人、家务和照顾家人的责任天然压给女儿。",
      "question_response": "为什么一说到照顾老人、做家务和操持家庭，最先被默认承担的总是女儿而不是所有子女一起？",
      "notes": "更偏“照护责任、家务责任和情绪劳动主要由女儿承担”的家庭分工话语，不主打继承或教育资源。",
      "priority": 48,
      "contexts": []
    },
    {
      "rule_id": "R055",
      "name": "彩礼/嫁妆/姓氏传承默认围绕男性",
      "must_include_any": ["女儿", "女孩", "闺女", "女生", "儿子", "男方", "男孩"],
      "must_include_any_2": ["嫁出去的人", "彩礼本来就是给男方的", "嫁妆得多陪一点", "孩子当然跟男方姓", "姓氏当然传给儿子", "女儿迟早要嫁出去", "女儿是别人家的人", "传宗接代靠儿子", "嫁出去就不是自家人", "生的孩子必须随男方姓", "香火要靠儿子", "香火得靠儿子", "没儿子香火就断了", "生女孩香火就断了", "生女儿香火就断了", "女儿接不了香火", "女孩接不了香火", "女孩不能传后", "女儿不能传后", "没有儿子就断后"],
      "exclude_any": ["姓氏可以协商", "孩子跟谁姓都可以", "反对默认跟男方姓", "彩礼嫁妆不该按性别压人", "孩子不一定跟男方姓", "姓氏不该只传儿子", "婚后归属不该默认偏男方", "不该把女儿当成嫁出去的人"],
      "labels": ["婚配制度规训", "姓氏传承偏置", "重男轻女"],
      "severity_default": "high",
      "confidence_default": "high",
      "surface_meaning_template": "说话者在把彩礼、嫁妆、姓氏和婚后归属默认围绕男性一侧来安排。",
      "hidden_structure_template": "这类表达把女性在婚配中的位置设定为“被嫁出、被转移、被归属”，同时把姓氏、后代和家族延续更多绑定在男性身上。",
      "impact_template": "可能让女性在婚配制度、后代命名和家庭归属上被放在更弱的位置，也会强化男性中心的家族观念。",
      "gentle_response": "婚配、姓氏和家庭安排都应该协商决定，而不是天然围绕男性一侧。",
      "boundary_response": "我不接受把女性默认成“嫁出去的人”，也不接受把姓氏和家族延续天然只绑定在男性身上。",
      "question_response": "为什么一说到彩礼、嫁妆、姓氏和婚后归属，就更容易默认围着男性一侧来安排，而不是平等协商？",
      "notes": "更偏“婚配制度、姓氏传承和婚后归属天然向男性倾斜”的规则，不主打继承资源本身。",
      "priority": 47,
      "contexts": []
    },
    {
      "rule_id": "R030",
      "name": "默认无明显性别结构",
      "must_include_any": [],
      "must_include_any_2": [],
      "exclude_any": [],
      "labels": ["不明显/无法判断"],
      "severity_default": "low",
      "confidence_default": "low",
      "surface_meaning_template": "当前句子中未检测到足够明确的性别角色或权力结构线索。",
      "hidden_structure_template": "这并不代表绝对没有问题，只是仅凭这句话无法做出较稳妥判断。",
      "impact_template": "建议结合上下文、说话者关系、语气和场景进一步判断。",
      "gentle_response": "这句话单独看不太够，我需要更多上下文才能更准确分析。",
      "boundary_response": "目前信息不足，先不做过度解读。",
      "question_response": "这句话是在什么场景下说的？前后还说了什么？",
      "notes": "兜底规则，避免过度解读。",
      "priority": 0,
      "contexts": []
    }
  ],
  contextOptions: ["不限", "职场", "家庭", "恋爱", "校园", "网络评论"],
  ruleContextMap: {
    R001: ["职场", "校园", "家庭"],
    R002: ["职场", "校园"],
    R003: ["家庭", "恋爱"],
    R004: ["家庭", "恋爱"],
    R005: ["家庭", "校园", "网络评论"],
    R006: ["家庭", "恋爱", "职场"],
    R007: ["职场", "恋爱", "家庭"],
    R008: ["职场", "恋爱", "家庭", "网络评论"],
    R009: ["家庭", "网络评论"],
    R010: ["校园", "职场"],
    R011: ["网络评论", "校园", "恋爱"],
    R012: ["恋爱", "家庭", "网络评论"],
    R013: ["家庭", "恋爱"],
    R014: ["恋爱", "家庭", "校园"],
    R015: ["恋爱", "家庭"],
    R016: ["家庭"],
    R017: ["职场", "家庭", "网络评论"],
    R018: ["恋爱", "家庭"],
    R019: ["网络评论", "家庭", "校园"],
    R020: ["家庭", "校园", "恋爱"],
    R021: ["职场", "家庭", "恋爱"],
    R022: ["家庭", "恋爱"],
    R023: ["网络评论", "家庭", "恋爱"],
    R024: ["家庭", "恋爱"],
    R025: ["职场"],
    R026: ["职场", "家庭", "校园"],
    R027: ["家庭", "校园"],
    R028: ["家庭", "恋爱"],
    R029: ["职场", "家庭", "网络评论"],
    R031: ["家庭", "恋爱", "网络评论"],
    R032: ["恋爱", "家庭", "网络评论"],
    R033: ["网络评论", "家庭", "校园"],
    R034: ["家庭", "职场", "恋爱"],
    R035: ["职场", "家庭", "网络评论"],
    R036: ["家庭", "恋爱"],
    R037: ["家庭", "恋爱"],
    R038: ["网络评论", "校园", "职场"],
    R039: ["职场", "恋爱", "家庭"],
    R040: ["恋爱", "家庭", "校园"],
    R041: ["网络评论", "恋爱", "家庭"],
    R042: ["职场", "网络评论", "恋爱"],
    R043: ["网络评论", "校园", "职场"],
    R044: ["家庭", "恋爱"],
    R045: ["恋爱", "家庭"],
    R046: ["恋爱", "家庭", "网络评论"],
    R047: ["网络评论", "职场", "家庭"],
    R048: ["家庭", "校园", "网络评论"],
    R049: ["家庭", "校园", "恋爱", "网络评论"],
    R050: ["网络评论", "恋爱", "校园"],
    R051: ["家庭", "恋爱"],
    R052: ["家庭", "校园"],
    R053: ["家庭"],
    R054: ["家庭"],
    R055: ["家庭", "恋爱"],
    R030: []
  },
  slotBlueprints: {
    R001: [
      ["女生", "女孩", "女人", "女的"],
      ["别", "不用", "不该", "没必要"],
      ["太拼", "别太拼", "不用太拼", "别那么拼", "这么拼", "太努力", "别太努力", "不用那么努力", "那么努力", "这么努力"],
      ["事业", "工作", "竞争", "发展", "家庭","上班"]
    ],
    R002: [
      ["女生", "女孩", "女人", "女的"],
      ["不适合当领导", "不适合做技术", "不适合搞技术", "当不了领导", "做不了领导", "不能当班长", "不适合当班长", "女生当不了班长"],
      ["逻辑不行", "理科不行", "脑子笨", "脑子不行", "脑子不好使", "什么都不懂"],
      ["领导", "技术", "理工", "编程", "管理", "班长", "带头", "压场"]
    ],
    R003: [
      ["女生", "女孩", "女人", "老婆", "媳妇"],
      ["要", "应该", "就该", "还是要", "该"],
      ["顾家", "带孩子", "做饭", "会做饭", "照顾家庭", "贤惠", "持家", "照顾老人"],
      ["家庭", "结婚", "婚后", "孩子"]
    ],
    R004: [
      ["女生", "女孩", "女人"],
      ["不用赚太多", "没必要赚那么多", "赚钱不是最重要", "少花点钱", "女生少花点钱", "女孩少花点钱", "女孩子少花点钱", "别花那么多", "别花那么多钱", "花钱别太大手大脚"],
      ["找个好老公就行", "嫁得好更重要", "依靠男人", "有人养就行", "找个男人就好了", "找个男人就行了"],
      ["经济独立", "买房", "花钱", "消费"]
    ],
    R005: [
      ["不像女生", "不像个女生", "不够女人", "没有女人味", "不像女孩"],
      ["穿衣", "打扮", "发型", "说话", "举止", "性格", "做派"],
      ["像女生", "女人味", "像个女孩", "女孩样", "女孩该有的样子"],
      ["你这样", "这样", "这么", "一点都不"]
    ],
    R006: [
      ["女生", "女孩", "女人"],
      ["温柔", "懂事", "听话", "贤惠", "乖一点", "别那么凶", "不要太调皮", "别太调皮", "不要有主见", "别有主见", "不要太有想法", "别太有想法", "别太有主意", "不要太有主意", "调皮"],
      ["要", "应该", "就该", "不要太", "别太"],
      ["顺从", "乖", "好管", "别闹"]
    ],
    R007: [
      ["你", "女生", "女孩", "女人"],
      ["太", "别那么", "这么", "不能", "不要"],
      ["强势", "太强势", "别那么强势", "太有攻击性", "咄咄逼人"],
      ["一点", "了", "吧", "在职场", "在会议上"]
    ],
    R008: [
      ["你", "女生", "女孩", "女人"],
      ["太", "很", "就是"],
      ["敏感", "太敏感", "想太多", "太情绪化", "玻璃心", "小题大做", "脾气差"],
      ["吧", "了", "而已", "我就开个玩笑"]
    ],
    R009: [
      ["女生", "女司机", "女人"],
      ["开车不行", "开车差", "不会开车", "车技差"],
      ["开车", "驾驶", "倒车", "停车", "上路"],
      ["就是", "本来就", "天生", "都这样"]
    ],
    R010: [
      ["女生", "女孩", "女人"],
      ["数学差", "理科差", "不适合理工", "不适合编程", "逻辑差", "脑子笨", "脑子不好使", "脑子转得慢", "不会用电脑", "不会写代码"],
      ["数学", "理科", "理工", "编程", "逻辑", "代码", "电脑"],
      ["学不会", "不行", "做不好", "不适合", "不会"]
    ],
    R011: [
      ["女生", "女孩", "女人"],
      ["漂亮", "好看", "颜值", "打扮", "瘦一点", "美", "变美", "长得好看更重要", "漂亮最重要", "女生要会打扮", "打扮一下更像女生", "女生要瘦一点", "女孩要瘦一点", "女生就爱减肥", "女生要漂亮", "女生要美", "女孩要漂亮", "女孩要美"],
      ["更重要", "最重要", "才行", "要会", "就该", "要漂亮", "要美", "不可以胖", "不能胖", "女生不能胖", "女孩不能胖", "女人不能胖", "女生不可以胖"],
      ["减肥", "控制体重", "少吃", "身材", "饭量", "胖"]
    ],
    R012: [
      ["胖", "瘦", "减肥", "身材"],
      ["再", "太", "这么", "已经"],
      ["没人要", "不好找对象", "嫁不出去", "不像女生", "少吃点", "吃这么多会胖", "女生还是少吃点", "女孩还是少吃点", "女生吃太多不好", "女孩子吃太多不好"],
      ["了", "以后", "将来", "真的", "会胖", "容易胖"]
    ],
    R013: [
      ["年纪大", "年龄大", "三十了", "三十多了", "老了"],
      ["就", "再", "已经", "都"],
      ["不好找对象", "嫁不出去", "抓紧结婚", "赶紧生孩子", "总归要结婚", "总是要结婚", "总会结婚", "女生总归要结婚", "女孩总归要结婚", "女人总会结婚", "女生总会结婚", "女孩总会结婚"],
      ["了", "以后", "再晚", "现在"]
    ],
    R014: [
      ["女生", "女孩", "女人"],
      ["谈太多恋爱不好", "太随便", "不检点", "名声不好", "女孩要矜持","玩的花"],
      ["恋爱", "对象", "感情经历", "谈过", "名声"],
      ["矜持", "随便", "检点", "体面"]
    ],
    R015: [
      ["女生", "女孩", "女人"],
      ["不要", "别", "不该", "要"],
      ["太主动", "主动", "先表白", "倒追", "别主动", "不要太主动", "要矜持", "太主动不好", "女追男不好"],
      ["不好", "不矜持", "掉价", "男生不会珍惜"]
    ],
    R016: [
      ["当妈", "妈妈", "做母亲", "有孩子了"],
      ["别这样", "该稳重点", "该把重心放家里", "要为孩子考虑"],
      ["孩子", "家庭", "家里", "妈妈"],
      ["稳重点", "顾家", "重心", "为孩子"]
    ],
    R017: [
      ["女强人"],
      ["不幸福", "没人要", "婚姻不好", "家庭不幸福"],
      ["婚姻", "家庭", "感情", "对象"],
      ["事业", "太强", "太能干", "强势"]
    ],
    R018: [
      ["老婆", "女友", "妻子", "对象"],
      ["就该支持我", "应该体谅我", "别给我添麻烦", "以我事业为主"],
      ["支持", "体谅", "事业", "配合"],
      ["我", "我的安排", "我的工作", "我的事业"]
    ],
    R019: [
      ["女生", "女孩", "女人"],
      ["别穿太暴露", "穿这么短", "穿成这样", "注意点形象", "容易出事", "穿得太少", "穿这么少", "穿太露了", "露太多了", "别穿这么露", "穿得这么暴露", "女生就该穿裙子", "女孩就该穿裙子", "穿裙子才像女生", "女生要穿裙子", "穿成这样不正经", "穿成这样不体面", "穿成这样不自爱", "女生别穿成这样出门"],
      ["穿着", "衣服", "裙子", "身材", "露", "暴露"],
      ["形象", "安全", "注意点", "检点", "不正经", "不体面", "不自爱"]
    ],
    R020: [
      ["女生", "女孩", "女人"],
      ["别喝酒", "别去喝酒", "别晚归", "别在外面待太晚", "晚上别乱跑", "女生晚上别自己回家", "女孩别去夜店", "女生别老往外跑", "女生晚上少出门", "不检点", "女生别喝那么多", "女生晚上别老在外面晃", "晚上别在外面玩那么晚", "女生别混夜场"],
      ["喝酒", "晚归", "夜店", "夜里", "晚上", "在外面", "回家", "夜场", "喝那么多"],
      ["不安全", "规矩", "检点", "注意", "太晚", "别玩太晚"]
    ],
    R021: [
      ["女生", "女孩", "女人"],
      ["别", "不要", "应该", "要"],
      ["这么冲", "别这么冲", "这么直接", "别这么直接", "顶嘴", "别顶嘴", "说话柔一点", "别这么凶", "要淑女", "淑女"],
      ["不礼貌", "不温柔", "会吃亏", "不像女生", "态度差", "凶","礼貌","温柔"]
    ],
    R022: [
      ["嫁得好", "找个好老公", "婚姻比事业重要", "找个男人就好了", "找个男人就行了", "该结婚", "就该结婚", "女人该结婚", "女生该结婚", "女孩该结婚", "女人就该结婚"],
      ["婚姻", "嫁人", "结婚", "老公", "男人"],
      ["比事业重要", "才是正路", "才是归宿", "更重要", "就行"],
      ["女生", "女孩", "女人", "女性"]
    ],
    R023: [
      ["女人就是", "女生就是", "女的都"],
      ["麻烦", "事多", "矫情", "难搞", "爱作"],
      ["都", "就是", "天生", "本来"],
      ["女人", "女生", "女的", "一群女的"]
    ],
    R024: [
      ["女人", "女生", "女孩", "老婆", "妻子"],
      ["生孩子是责任", "总要生孩子", "不生不完整", "要给家里传宗接代"],
      ["生孩子", "当妈", "传宗接代", "完整"],
      ["责任", "义务", "总要", "必须"]
    ],
    R025: [
      ["情绪", "不理性", "太感性"],
      ["领导", "管理", "决策", "女生"],
      ["当领导", "做管理", "做决定", "拍板"],
      ["别那么", "不能", "不适合", "别太"]
    ],
    R026: [
      ["你一个女生", "一个女孩", "作为女人"],
      ["怎么敢", "怎么能", "居然敢", "还敢"],
      ["这样", "这么做", "这么说", "顶嘴"],
      ["越界", "本分", "分寸", "身份"]
    ],
    R027: [
      ["女孩家家", "一个女孩", "女孩就该"],
      ["规矩", "体面", "矜持", "老实", "安分"],
      ["别这样", "不要这样", "怎么能这样", "要像个女孩"],
      ["女孩", "女生", "女人"]
    ],
    R028: [
      ["结婚后", "婚后", "结婚"],
      ["以家庭为主", "重心回归家庭", "别折腾事业了", "为了家牺牲一点"],
      ["家庭", "事业", "重心", "牺牲"],
      ["女人", "女生", "老婆", "妻子"]
    ],
    R029: [
      ["女生", "女人", "女孩"],
      ["别抛头露面", "低调一点", "别太出风头", "别总在外面"],
      ["抛头露面", "出风头", "外面", "公开"],
      ["低调", "安分", "少露面", "别总出来"]
    ],
    R031: [
      ["女人", "女生", "女孩", "女性", "剩女", "大龄剩女", "大龄女", "三十多的女的", "年纪大的女人"],
      ["年纪大", "年龄大", "过了三十", "三十以后", "大龄", "岁数大了", "三十多了"],
      ["贬值", "掉价", "不值钱", "剩下了", "没人要", "越老越不值钱", "早点嫁","嫁不出去","难嫁", "年纪大了没人要", "过了三十就不值钱", "老剩女", "越老越掉价", "年纪一大就贬值", "大龄就很难嫁", "三十多就难嫁了"],
      ["婚恋", "结婚", "相亲", "对象", "市场", "条件", "嫁"]
    ],
    R032: [
      ["女生", "女孩", "女人", "女性", "女的"],
      ["二手", "二手货", "掉价", "贬值", "不值钱", "像被用过", "不干净了", "像二手货", "二手女人", "不清白了", "有过男人就掉价", "谈过就不值钱","赔钱"],
      ["谈过", "睡过", "有经历", "不干净", "不纯洁", "不清白"],
      ["恋爱", "关系", "名声", "洁身自好", "自爱", "清白","单纯"]
    ],
    R033: [
      ["骚扰", "侵犯", "被占便宜", "被猥亵", "被强奸", "出事", "被欺负", "被尾随"],
      ["谁让你", "活该", "怪你自己", "你自己导致的", "你自己不注意", "自找的", "也是你自己问题", "那也是你自找的", "谁叫你这样", "出事也怪你", "不怪别人怪你自己", "出事别怪别人", "被骚扰也怪你自己", "被侵犯也是你自己问题", "谁让你晚上还在外面", "谁让你一个人去"],
      ["穿成那样", "喝酒", "晚归", "一个人出门", "不检点", "穿那么少", "晚上还在外面", "一个人去那种地方"],
      ["别怪别人", "不怪别人怪你", "自己负责", "那就怪你自己"]
    ],
    R034: [
      ["例假", "月经", "大姨妈", "怀孕", "孕妇", "经期", "生理期"],
      ["矫情", "别这么矫情", "作", "情绪化", "玻璃心", "闹", "激素问题", "别拿这个说事", "别这么玻璃心", "是不是来大姨妈了", "是不是经期到了", "是不是怀孕了才这样", "来例假就别闹了"],
      ["激素问题", "荷尔蒙", "生理期", "来那个了", "经期到了"],
      ["拿这个说事", "是不是来大姨妈了", "是不是怀孕了", "又是激素作怪"]
    ],
    R035: [
      ["女人", "女生", "女性", "女孩", "女的"],
      ["不理性", "天生感性", "感情用事", "做决定靠情绪", "不够理智", "什么都不懂", "脑子不清楚", "理智不了", "女人就是不理智", "女生本来就感性", "女的做事靠感觉", "女人天生不适合做决定"],
      ["天生", "本来就", "就是这样", "骨子里"],
      ["决策", "判断", "领导", "管理", "做主", "拿主意"]
    ],
    R036: [
      ["男主外女主内", "男人负责赚钱", "女人负责顾家", "男人在外面", "女人在家里", "男外女内"],
      ["本来就这样", "天经地义", "自然规律", "自古如此", "本来就合理", "本该如此", "很正常", "自古以来都这样", "老祖宗就是这么定的", "本来就该这么分工", "这才是正常家庭"],
      ["顾家", "养家", "带孩子", "在家里", "在外面", "照顾家庭"],
      ["传统", "正常", "应该如此", "正经家庭", "规矩"]
    ],
    R037: [
      ["女人", "女生", "女性", "老婆", "妻子", "女的"],
      ["生孩子", "当妈", "生育", "传宗接代", "生一个"],
      ["有什么用", "没价值", "不完整", "白当女人", "没意义", "不生孩子有什么用", "不当妈有什么用", "女人就是要生孩子", "生不了就没价值", "不生就白当女人", "不生就是不完整", "不生孩子算什么女人", "女人总得生一个", "不当妈人生不完整", "女人的用处就是生孩子"],
      ["总得生", "就是要生", "迟早要生", "必须生"]
    ],
    R038: [
      ["女生", "女人", "女孩", "女性", "女的"],
      ["化妆", "精致", "打扮", "收拾自己", "带妆", "像样", "就该化妆", "必须精致", "女人就要精致一点", "出门化个妆", "女生要懂打扮", "不化妆不像样", "女生出门得收拾一下", "女孩见人要精致点", "出门素颜不合适", "女的就得打扮得体"],
      ["就该", "必须", "要", "应该", "得", "起码得"],
      ["出门", "日常", "见人", "像样", "上班", "出席场合", "素颜", "收拾一下"]
    ],
    R039: [
      ["女生", "女人", "女性", "女强人", "优秀女人", "太能干的女人"],
      ["太优秀", "太强", "太独立", "太厉害", "太能干", "条件太好", "赚太多", "职位太高", "学历太高"],
      ["男人不敢要", "没人敢娶", "婚姻不会好", "不好找对象", "男人受不了", "没人敢追", "男的有压力", "太优秀男人不敢要", "太强没人敢娶", "太厉害男人会怕", "事业太强婚姻不会好", "太独立不好找对象", "优秀的女人难嫁", "女人太能干男人受不了", "太会赚钱男人有压力", "条件太好反而没人要", "太强势男人不会喜欢", "赚太多男人受不了", "职位太高男人有压力", "学历太高不好找对象"],
      ["事业", "收入", "能力", "成就", "赚钱", "职位", "学历"]
    ],
    R040: [
      ["女生", "女孩", "女人", "女性", "女的"],
      ["干净", "不干净", "纯洁", "不纯洁", "洁身自好", "清白", "要干净一点", "太脏了", "名声会坏", "女孩还是要洁身自好", "女孩要自爱", "别把自己搞脏了", "谈多了就不干净了", "女的还是要检点"],
      ["名声", "关系经历", "谈恋爱", "睡过", "检点", "自爱","单纯"],
      ["还是要", "应该", "要", "最好", "得"]
    ],
    R041: [
      ["女生", "女孩", "女人", "女性"],
      ["老了就不好看", "年纪大了就不好看", "一老就不值钱", "老得快", "女人老得快", "没魅力", "过了年纪就没魅力", "女生老了就没人看"],
      ["年纪大", "老了", "过了年纪", "年龄上去"],
      ["没人看", "没价值", "不值钱", "没吸引力"]
    ],
    R042: [
      ["女生就是", "女人就是", "女孩就是", "女的就是"],
      ["事多", "难带", "麻烦", "难搞", "不好合作", "带不动", "情绪多"],
      ["职场", "合作", "团队", "相处", "沟通"],
      ["不好带", "麻烦得很"]
    ],
    R043: [
      ["女生", "女孩", "女人", "女的"],
      ["别一个人去", "不该一个人去", "不适合一个人去", "别去那种地方", "不适合做这个职业", "别去跑长途", "别走夜路", "别一个人旅行", "不适合单独出差", "女生别自己去", "别自己去外地", "别一个人去那种地方", "女生别单独去", "女生不适合跑夜班"],
      ["一个人旅行", "跑长途", "夜班", "出远门", "夜路", "单独出差", "自己去", "外地", "单独去", "那种地方"],
      ["危险", "不安全", "不适合", "别去", "一个人", "单独"]
    ],
    R044: [
      ["当妈了", "有孩子了", "做妈妈了", "当母亲了", "孩子都有了"],
      ["孩子最重要", "别只想着自己", "先顾孩子", "还折腾什么事业", "别打扮了", "重心放孩子身上"],
      ["事业", "打扮", "出门", "工作", "自己"],
      ["孩子", "家庭", "母亲", "妈妈"]
    ],
    R045: [
      ["她就该", "老婆就该", "女友就该", "对象就该", "女人就该配合"],
      ["配合我", "别拖我后腿", "别影响我", "围着我转", "跟着我安排", "以我为主"],
      ["事业", "安排", "节奏", "计划", "生活"],
      ["让步", "迁就", "听我的", "跟着我"]
    ],
    R046: [
      ["女生", "女孩", "女人", "女性"],
      ["主见太多不好嫁", "太会说不好嫁", "太有想法不好找对象", "太有主见男人不喜欢", "嘴太厉害不好嫁", "太会表达男人受不了", "有主见不好", "太有主意不好嫁", "太有想法男人不喜欢"],
      ["主见", "会说", "有想法", "有主意", "表达", "嘴厉害"],
      ["不好嫁", "不好找对象", "男人不喜欢", "男人受不了"]
    ],
    R047: [
      ["女生", "女孩", "女人", "女性", "女的"],
      ["爱花钱", "花钱多", "花钱厉害", "喜欢花钱", "拜金", "买买买", "只会买买买"],
      ["乱花钱", "消费欲强", "不理性消费", "只会花钱","爱收礼物"],
      ["消费", "买东西", "购物", "物质", "收礼物"]
    ],
    R048: [
      ["女生", "女孩", "女人", "女性", "女的"],
      ["软弱", "脆弱", "爱哭", "胆子小", "经不起事", "太软弱", "太脆弱", "动不动就哭", "一说就哭"],
      ["太", "很", "就是", "动不动就", "一说就"],
      ["哭", "扛不住", "受不了", "撑不住"]
    ],
    R049: [
      ["女生", "女孩", "女人", "女性"],
      ["女生要吃得少", "女孩要吃得少", "女生吃得少", "女孩吃得少", "女生要少吃点", "女孩要少吃点", "女生就该少吃点", "女人要少吃点", "女生别吃那么多", "女孩别吃那么多", "女生饭量要小一点", "女孩饭量要小一点", "女孩子要控制饭量", "女人饭量别太大", "女生饭量别那么大", "吃太多不像女生", "吃相不像女生", "女生吃饭要斯文一点", "女生吃饭别那么猛", "女孩子饭量别太大", "女孩吃饭别狼吞虎咽", "女生别吃太快", "女孩别吃太快", "女生吃饭要文雅点", "女人吃饭斯文点"],
      ["少吃", "吃得少", "饭量小", "控制饭量", "饭量别太大", "饭量别那么大", "吃相", "斯文一点", "文雅点", "别那么猛", "别吃太快", "狼吞虎咽"],
      ["就该", "要", "应该", "才像女生", "不像女生", "别"]
    ],
    R050: [
      ["女生", "女孩", "女人", "女的", "女的之间", "女人之间"],
      ["雌竞", "爱雌竞", "就会雌竞", "勾心斗角", "互相嫉妒", "互相攀比", "争风吃醋", "女人何苦为难女人", "女人之间都是宫斗", "女的就爱抢男人", "女的最爱互撕", "女生就是喜欢比来比去", "女人之间就会斗来斗去", "女生最会搞小团体", "女生最爱抱团排挤", "女人之间最爱玩心眼", "女的就是一股茶味", "女生都很茶", "绿茶婊", "白莲花", "雌竞脑"],
      ["互相", "之间", "抢男人", "宫斗", "攀比", "嫉妒", "互撕", "小团体", "排挤", "茶", "绿茶", "白莲花"],
      ["就是", "都", "天然", "最爱", "特别会", "很会", "脑子里全是"]
    ],
    R051: [
      ["女孩", "女儿", "闺女", "生女孩", "生女儿", "生女生"],
      ["不好", "不如儿子", "还是儿子好", "没用", "赔钱", "不值钱", "白养", "没有儿子不行", "生儿子才行", "女儿就是别人家的人", "生女儿没福气", "生个女儿有什么用", "女孩终究靠不住", "没儿子不算圆满", "闺女迟早是别人家的", "断香火", "没男丁", "招弟", "来弟", "盼儿子", "传宗接代必须靠儿子", "没儿子抬不起头", "女儿不能继后", "生女儿亏本", "养女儿没回报", "女儿不能养老", "养女儿不划算", "女儿是赔本买卖", "养闺女没用", "生女生没用", "生女孩也没用", "生女儿也没用", "不要生女孩", "不要生女儿", "别生女孩", "别生女儿"],
      ["儿子", "传宗接代", "赔钱货", "别人家", "香火", "男丁", "后代", "宗", "传后", "继后", "宗族", "养老", "回报", "划算","香火"],
      ["还是", "才", "就", "总归", "终究", "得", "必须", "根本"]
    ],
    R052: [
      ["女孩", "女儿", "闺女", "女生"],
      ["读那么多书没用", "不用读太多书", "没必要供她读书", "女孩子读书没用", "培养女孩不划算", "资源该给儿子", "供女儿上学不值得", "女孩读那么高干嘛", "女儿书读多了也没用", "投资女儿不如投资儿子"],
      ["读书", "上学", "培养", "资源", "投资", "供", "教育"],
      ["没用", "不值得", "不划算", "不如儿子", "该给儿子"]
    ],
    R053: [
      ["女儿", "女孩", "闺女", "儿子", "男孩"],
      ["房子留给儿子", "家产当然给儿子", "女儿不用分那么多", "嫁出去的女儿泼出去的水", "财产该给儿子", "家里的东西要留给儿子", "女儿没资格分家产", "房产应该给儿子", "儿子才有继承权", "女儿不用争家产"],
      ["房子", "家产", "财产", "分家", "继承", "房产", "资格"],
      ["给儿子", "留给儿子", "不用分", "没资格", "才有"]
    ],
    R054: [
      ["女儿", "女孩", "闺女", "女生"],
      ["照顾老人本来就是女儿的事", "女儿就该伺候父母", "照顾爸妈主要靠女儿", "家务本来就该女儿做", "闺女就该多顾家里", "女儿得多照顾弟弟", "照顾家里应该是女孩的责任", "女儿就得多操心家里", "家里老人主要靠女儿照顾", "女孩就该会照顾人"],
      ["照顾老人", "伺候父母", "家务", "顾家", "照顾弟弟", "操心家里", "照顾人"],
      ["就该", "本来就是", "主要靠", "应该是", "得"]
    ],
    R055: [
      ["女儿", "女孩", "闺女", "女生", "儿子", "男方", "男孩"],
      ["嫁出去的人", "彩礼本来就是给男方的", "嫁妆得多陪一点", "孩子当然跟男方姓", "姓氏当然传给儿子", "女儿迟早要嫁出去", "女儿是别人家的人", "传宗接代靠儿子", "嫁出去就不是自家人", "生的孩子必须随男方姓", "香火要靠儿子", "香火得靠儿子", "没儿子香火就断了", "生女孩香火就断了", "生女儿香火就断了", "女儿接不了香火", "女孩接不了香火", "女孩不能传后", "女儿不能传后", "没有儿子就断后"],
      ["彩礼", "嫁妆", "男方", "跟男方姓", "姓氏", "传宗接代", "嫁出去", "香火", "断后", "传后", "继后"],
      ["当然", "本来就是", "必须", "迟早", "得"]
    ]
  },
  slotConfigMap: {
    R001: { requiredIndexes: [0, 2], weightMap: { 0: 2, 1: 1, 2: 3, 3: 1 } },
    R002: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 2, 3: 1 } },
    R003: { requiredIndexes: [0, 2], weightMap: { 0: 2, 1: 1, 2: 3, 3: 1 } },
    R004: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 2, 2: 3, 3: 1 } },
    R005: { requiredIndexes: [0], weightMap: { 0: 3, 1: 1, 2: 1, 3: 1 } },
    R006: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R007: { requiredIndexes: [2], weightMap: { 0: 1, 1: 1, 2: 3, 3: 1 } },
    R008: { requiredIndexes: [2], weightMap: { 0: 1, 1: 1, 2: 3, 3: 1 } },
    R009: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R010: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R011: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 2, 2: 3, 3: 1 } },
    R012: { requiredIndexes: [0, 2], weightMap: { 0: 2, 1: 1, 2: 3, 3: 1 } },
    R013: { requiredIndexes: [2], weightMap: { 0: 1, 1: 1, 2: 3, 3: 1 } },
    R014: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R015: { requiredIndexes: [2], weightMap: { 0: 1, 1: 1, 2: 3, 3: 1 } },
    R016: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R017: { requiredIndexes: [0, 1], weightMap: { 0: 3, 1: 3, 2: 1, 3: 1 } },
    R018: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R019: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R020: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R021: { requiredIndexes: [2], weightMap: { 0: 1, 1: 1, 2: 3, 3: 1 } },
    R022: { requiredIndexes: [0, 1], weightMap: { 0: 3, 1: 2, 2: 1, 3: 1 } },
    R023: { requiredIndexes: [0, 1], weightMap: { 0: 3, 1: 3, 2: 1, 3: 1 } },
    R024: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R025: { requiredIndexes: [0, 1], weightMap: { 0: 3, 1: 2, 2: 1, 3: 1 } },
    R026: { requiredIndexes: [0, 1], weightMap: { 0: 3, 1: 3, 2: 1, 3: 1 } },
    R027: { requiredIndexes: [0], weightMap: { 0: 3, 1: 1, 2: 1, 3: 1 } },
    R028: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R029: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R031: { requiredIndexes: [2], weightMap: { 0: 1, 1: 2, 2: 3, 3: 2 } },
    R032: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R033: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R034: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R035: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R036: { requiredIndexes: [0, 1], weightMap: { 0: 3, 1: 2, 2: 1, 3: 1 } },
    R037: { requiredIndexes: [1, 2], weightMap: { 0: 1, 1: 2, 2: 3, 3: 1 } },
    R038: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R039: { requiredIndexes: [1, 2], weightMap: { 0: 1, 1: 2, 2: 3, 3: 2 } },
    R040: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R041: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R042: { requiredIndexes: [0, 1], weightMap: { 0: 3, 1: 3, 2: 1, 3: 1 } },
    R043: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R044: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R045: { requiredIndexes: [0, 1], weightMap: { 0: 3, 1: 3, 2: 1, 3: 1 } },
    R046: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R047: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R048: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R049: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R050: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R051: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R052: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R053: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R054: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } },
    R055: { requiredIndexes: [0, 1], weightMap: { 0: 2, 1: 3, 2: 1, 3: 1 } }
  },
  aliasMap: {
    "不好找对象": ["很难找对象", "不容易找对象", "很难找到对象", "不好找到对象", "难嫁"],
    "没人要": ["没人看得上", "没有男人要", "没人肯娶"],
    "嫁不出去": ["嫁不掉", "很难嫁出去", "不好嫁"],
    "太主动": ["太积极", "太上赶着", "太快表白", "太主动男人不会珍惜", "太往前冲", "主动过头"],
    "主动": ["先表白", "先开口", "倒追", "主动追", "先追", "先示好", "先联系", "先去追"],
    "太拼": ["那么拼", "这么拼", "这么努力", "那么努力", "这么要强", "事业心这么重", "这么卷"],
    "别太拼": ["没必要这么要强", "别搞得事业心这么重", "女生别这么卷", "差不多就行"],
    "顾家": ["照顾家里", "带孩子", "持家"],
    "少花点钱": ["别花那么多钱", "少花一点", "花钱省着点", "别总乱花钱", "别那么能花", "少买点"],
    "爱花钱": ["花钱多", "花钱厉害", "喜欢花钱"],
    "找个好老公就行": ["有人养就行", "靠男人就行", "以后有人养你", "找个男人就够了", "找个靠谱男人就好了"],
    "找个男人就好了": ["找个男人就行了", "有男人就行", "找个人养着就行", "找个靠谱男人就行"],
    "贤惠": ["有个女人样", "懂得持家", "会持家"],
    "调皮": ["太闹", "不老实", "疯疯癫癫"],
    "乖一点": ["听话一点", "安分一点", "老实一点"],
    "不要有主见": ["别有主见", "女生不要有主见", "女孩不要有主见", "女人不要有主见", "女人不能有主见"],
    "不要太有想法": ["别太有想法", "不要那么有想法", "别那么有想法", "不要太有主意", "别太有主意"],
    "软弱": ["脆弱", "胆小", "扛不住"],
    "爱哭": ["一说就哭", "动不动就哭", "老爱哭"],
    "太敏感": ["过于敏感", "有点敏感", "你反应太大了"],
    "想太多": ["想多了", "脑补太多", "别脑补", "别多想"],
    "小题大做": ["至于吗", "开不起玩笑", "别上纲上线"],
    "太强势": ["过于强势", "太有压迫感", "控制欲太强", "压迫感太强", "太硬了"],
    "咄咄逼人": ["很冲", "太咄咄逼人", "说话逼人", "太咄咄了"],
    "这么冲": ["太冲", "很冲", "说话很冲", "态度别这么差"],
    "说话柔一点": ["说话温柔一点", "说话别太硬", "女人说话柔和点"],
    "不适合当领导": ["不能当班长", "不适合当班长", "当不了班长", "女生不可以当班长"],
    "脑子笨": ["脑子不行", "脑子不好使"],
    "脑子不好使": ["脑子不好", "脑子慢", "反应慢"],
    "脑子转得慢": ["脑子转得不快", "反应慢半拍", "转不过弯"],
    "什么都不懂": ["啥都不懂", "根本不懂", "一点不懂"],
    "不礼貌": ["没礼貌", "太没礼貌"],
    "会吃亏": ["容易吃亏", "以后会吃亏"],
    "年纪大": ["年龄大", "岁数大"],
    "三十多了": ["30多了", "都30多了", "已经三十多了"],
    "抓紧结婚": ["赶紧结婚", "尽快结婚"],
    "总归要结婚": ["总是要结婚", "迟早要结婚", "总会结婚", "该结婚", "就该结婚"],
    "赶紧生孩子": ["快点生孩子", "早点生孩子"],
    "吃得少一点": ["少吃一点", "吃得少", "少吃点"],
    "漂亮最重要": ["要漂亮", "要美", "要变美", "漂亮才行"],
    "女生要瘦一点": ["女孩要瘦一点", "女生要苗条一点", "女生要瘦点"],
    "不能胖": ["不可以胖", "还是瘦点好", "不能长胖"],
    "女生就爱减肥": ["女孩就爱减肥", "女生本来就爱减肥", "女的都爱减肥", "天天就知道减肥", "总想着减肥"],
    "贬值": ["掉价", "不值钱"],
    "二手": ["二手货", "像二手的一样"],
    "谁让你": ["活该", "你自己不注意", "怪你自己", "你自己导致的", "出事别怪别人", "谁让你晚上还在外面", "谁让你一个人去"],
    "怪你自己": ["那就怪你自己", "出了事怪你自己", "被骚扰也怪你自己", "被侵犯也是你自己问题"],
    "别矫情": ["别作", "别情绪化"],
    "天生感性": ["女人就是感性", "女人就是不理性", "做决定靠情绪"],
    "男主外女主内": ["男人负责赚钱", "女人负责顾家", "男的在外面女的在家里"],
    "本来就这样": ["天经地义", "自然规律", "自古如此", "本来就合理"],
    "不生孩子有什么用": ["不当妈有什么用", "不生就白当女人", "生不了就没价值", "不生孩子有什么意义", "女人不生孩子图什么"],
    "就该化妆": ["出门化个妆", "女生要懂打扮", "要打扮"],
    "太优秀男人不敢要": ["太强没人敢娶", "优秀的女人难嫁", "太独立不好找对象"],
    "要干净一点": ["不纯洁", "不干净", "太脏了", "洁身自好"],
    "剩女": ["大龄剩女", "老剩女"],
    "掉价": ["很掉价", "会掉价", "显得掉价"],
    "不值钱": ["越来越不值钱", "就不值钱了"],
    "二手货": ["二手女人", "像被人用过的一样"],
    "不干净": ["不清白", "不纯了", "脏了"],
    "谁让你穿成那样": ["谁叫你穿成那样", "你穿成那样不怪别人", "谁让你穿这么露", "谁让你穿那么少"],
    "活该": ["自找的", "你活该"],
    "大姨妈": ["来姨妈", "来例假", "来月经"],
    "别这么矫情": ["别那么矫情", "矫情什么"],
    "不理性": ["没脑子", "脑子不清楚", "不够理智", "女人天生脾气差"],
    "感情用事": ["情绪做决定", "总被情绪带着走"],
    "自然规律": ["本性如此", "老祖宗留下来的"],
    "不生孩子算什么女人": ["不生孩子算什么女的", "女人不生孩子有啥意义"],
    "必须精致": ["必须漂漂亮亮", "得活得精致", "要精致一点", "得精致一点"],
    "化妆": ["化个妆", "收拾一下脸", "带妆", "化点妆", "稍微打扮一下"],
    "太优秀": ["太能干", "太出色", "条件太好"],
    "男人不敢要": ["男人受不了", "男的不敢追", "没人敢追"],
    "洁身自好": ["守妇道", "女孩要自爱"],
    "名声会坏": ["名声不好", "把名声搞坏了"],
    "检点": ["不检点", "要检点一点"],
    "过了三十": ["三十以后", "过了30", "一过三十"],
    "大龄": ["年龄上去了", "岁数上去了", "一把年纪"],
    "难嫁": ["不好嫁", "很难嫁", "嫁不动了"],
    "谈过": ["谈过对象", "谈过恋爱", "有前任"],
    "睡过": ["跟人睡过", "跟男人睡过", "有过性经历"],
    "不清白": ["名声不清白", "已经不清白了"],
    "骚扰": ["性骚扰", "骚扰你", "被骚扰了"],
    "侵犯": ["性侵", "侵犯你", "被侵犯了"],
    "穿成那样": ["穿那么少", "穿这么露", "穿得这么暴露", "穿得太少", "穿这么少", "穿太露了", "露太多了", "别穿这么露", "穿成这样不正经", "穿成这样不体面", "穿成这样不自爱"],
    "女生就该穿裙子": ["女孩就该穿裙子", "穿裙子才像女生", "女生要穿裙子", "女人就该穿裙子", "女生得穿裙子", "女孩得穿裙子"],
    "晚归": ["回来太晚", "大半夜回家", "这么晚还在外面"],
    "别喝酒": ["别去喝酒", "别在外面喝酒", "女孩子少喝酒", "女生最好别喝酒", "女生别喝那么多", "女孩别老喝酒"],
    "别晚归": ["别回来太晚", "晚上别在外面待太晚", "女孩子别老在外面晃", "女生晚上别老在外面晃", "晚上别在外面玩那么晚"],
    "来那个了": ["来事了", "来例假了", "来姨妈了"],
    "怀孕": ["有身子了", "怀着孕", "挺着肚子"],
    "激素问题": ["荷尔蒙问题", "都是激素闹的", "就是激素作怪"],
    "女人就是不理性": ["女人本来就不理性", "女的就是不理智"],
    "做决定靠情绪": ["做事靠情绪", "总按情绪做决定", "一上头就乱决定"],
    "男人负责赚钱": ["男人就该养家", "男的负责挣钱", "男人出去打拼"],
    "女人负责顾家": ["女人在家带孩子", "女人就该照顾家庭", "女的顾家就行"],
    "不当妈有什么用": ["女人不当妈有什么意义", "不生不养有什么用"],
    "传宗接代": ["给家里留后", "给家里续香火", "延续香火","香火"],
    "出门化个妆": ["出门至少化个妆", "见人先化妆", "出门先收拾收拾", "出门先打扮一下"],
    "不化妆不像样": ["素颜见人不像样", "不收拾自己不像样", "不打扮不体面", "素颜出门不合适"],
    "太独立不好找对象": ["太独立男人不喜欢", "太要强不好嫁", "太会赚钱不好找对象"],
    "优秀的女人难嫁": ["太优秀的女人难嫁", "女人太优秀不好嫁", "越优秀越难嫁"],
    "男人受不了": ["男的受不了", "男人会怕", "男的有压力"],
    "老了就不好看": ["年纪大了就不好看", "一老就不好看"],
    "一老就不值钱": ["老了就不值钱", "年纪大了就掉价"],
    "事多": ["麻烦", "难搞"],
    "难带": ["不好带", "带不动"],
    "别一个人去": ["不要一个人去", "别单独去", "别自己去", "女生别自己去", "别自己去外地", "别一个人去那种地方", "女生别单独去"],
    "不适合做这个职业": ["不适合做这行", "不适合干这个", "干不了这个", "不适合跑这种工作", "不适合做这种工作", "女生不适合跑夜班", "女人不适合干这种活"],
    "孩子最重要": ["先顾孩子", "孩子第一", "孩子排第一"],
    "别只想着自己": ["别总想着自己", "不能只顾自己", "别只顾自己"],
    "配合我": ["按我的来", "听我的", "跟着我"],
    "别拖我后腿": ["别给我拖后腿", "别影响我", "别耽误我"],
    "主见太多不好嫁": ["太有主见不好嫁", "主意太多不好嫁", "有主见不好嫁", "女生太有主见了不好", "太有主意不好嫁", "太有想法男人不喜欢"],
    "太会说不好嫁": ["嘴太厉害不好嫁", "太会表达不好嫁", "太能说不好嫁"],
    "赚太多": ["赚得太多", "收入太高", "太会赚钱"],
    "职位太高": ["位置太高", "级别太高", "当得太高"],
    "学历太高": ["书读太多", "学历太好", "太高学历"],
    "清白": ["身子清白", "名声清白"],
    "自爱": ["女孩要爱惜自己", "女孩要懂得自重", "要守住自己"],
    "少吃点": ["还是少吃点", "最好少吃点", "女孩要少吃点"],
    "女生要吃得少": ["女孩要吃得少", "女生吃得少", "女孩吃得少", "女生要少吃点", "女孩要少吃点", "女生就该少吃点", "女人要少吃点", "女生别吃那么多", "女孩别吃那么多", "女生饭量要小一点", "女孩饭量要小一点", "女孩子要控制饭量", "女人饭量别太大", "女生饭量别那么大", "吃太多不像女生", "女生吃饭要斯文一点", "女生吃饭别那么猛", "女孩子饭量别太大", "女孩吃饭别狼吞虎咽", "女生别吃太快", "女孩别吃太快", "女生吃饭要文雅点", "女人吃饭斯文点"],
    "吃相不像女生": ["女孩子吃相别那样", "女生吃相太难看了", "女生吃饭别那么粗鲁", "吃饭这样不像女生", "女生吃饭要文雅点"],
    "吃这么多会胖": ["吃这么多容易胖", "吃太多会胖", "吃那么多会长胖"],
    "雌竞": ["雌性竞争", "女的就爱雌竞", "女生就是爱雌竞", "女人就是雌竞", "女的天生雌竞"],
    "勾心斗角": ["互相算计", "明争暗斗", "互相使绊子", "斗来斗去"],
    "互相嫉妒": ["见不得对方好", "互相眼红", "彼此嫉妒", "就爱眼红别人"],
    "争风吃醋": ["抢男人", "为男人斗来斗去", "为了男人互撕", "围着男人转"],
    "女人之间都是宫斗": ["女生之间都是宫斗", "女的之间就是宫斗", "女人之间就那点事", "女的最爱互撕"],
    "女的就爱抢男人": ["女生就爱抢男人", "女人最爱抢男人", "女的就喜欢抢男人"],
    "女生最会搞小团体": ["女的最会搞小团体", "女生就喜欢拉帮结派", "女人最爱抱团排挤别人"],
    "女生最爱抱团排挤": ["女人最爱抱团排挤", "女的最爱抱团排外", "女生就喜欢排挤别人"],
    "女人之间最爱玩心眼": ["女生之间最爱玩心眼", "女的最会玩心眼", "女人最会耍心机"],
    "女生都很茶": ["女的都很茶", "女生就是茶", "一股绿茶味", "特别茶"],
    "绿茶婊": ["绿茶精", "一股绿茶味", "装绿茶", "茶里茶气"],
    "白莲花": ["装纯", "装无辜", "装可怜", "白莲花那一套"],
    "雌竞脑": ["满脑子雌竞", "脑子里全是雌竞", "一天到晚雌竞"],
    "生女孩不好": ["生女儿不好", "生闺女不好", "女孩不好", "生个女儿不好", "生女生不好", "生女生没用", "生女孩也没用", "生女儿也没用", "不要生女孩", "不要生女儿", "别生女孩", "别生女儿"],
    "还是儿子好": ["还是生儿子好", "儿子更好", "男孩更好", "还是男孩好", "还是得生儿子"],
    "不如儿子": ["女儿不如儿子", "女孩不如男孩", "还是儿子更值钱", "闺女哪有儿子好"],
    "没用": ["没什么用", "不顶用", "没价值"],
    "赔钱": ["赔钱货", "赔钱玩意", "养女儿赔钱", "女儿就是赔钱货"],
    "女儿就是别人家的人": ["闺女都是别人家的", "女儿终归是别人家的", "养女儿是给别人养", "闺女迟早是别人家的"],
    "生个女儿有什么用": ["生女儿有什么用", "生个闺女有什么用", "生女孩有什么用"],
    "女孩终究靠不住": ["女儿终究靠不住", "闺女靠不住", "女孩指望不上"],
    "没儿子不算圆满": ["没儿子不完整", "没有儿子总差点意思", "家里没儿子不行"],
    "断香火": ["断了香火", "要断香火了", "香火断了"],
    "没男丁": ["家里没男丁", "没有男丁", "没个男丁"],
    "招弟": ["招弟来弟", "名字都得叫招弟", "生个招弟"],
    "来弟": ["来个弟弟", "盼个弟弟", "名字叫来弟"],
    "盼儿子": ["盼个儿子", "就盼着生儿子", "一直想要个儿子"],
    "传宗接代必须靠儿子": ["传宗接代得靠儿子", "延续香火必须靠儿子", "传后只能靠儿子"],
    "没儿子抬不起头": ["没有儿子抬不起头", "家里没儿子没脸见人", "没儿子腰杆都不硬"],
    "女儿不能继后": ["女儿不能传宗接代", "女儿不能继承香火", "闺女不能继后"],
    "生女儿亏本": ["生闺女亏本", "养女儿亏本", "女儿就是亏本"],
    "养女儿没回报": ["养闺女没回报", "养女儿没有回报", "养女儿回不了本"],
    "女儿不能养老": ["闺女不能养老", "女儿养老靠不住", "养女儿指望不上养老"],
    "养女儿不划算": ["养闺女不划算", "养女儿太不划算", "生女儿不划算"],
    "女儿是赔本买卖": ["闺女是赔本买卖", "养女儿就是赔本买卖", "生女儿就是赔本买卖"],
    "养闺女没用": ["养女儿没用", "生闺女没用", "闺女没什么用"],
    "读那么多书没用": ["书读那么多没用", "女孩子读那么多书没必要", "女孩书读多了没用"],
    "不用读太多书": ["女孩子不用读太多书", "女孩没必要读太多书", "读那么高没必要"],
    "没必要供她读书": ["没必要供女儿读书", "女儿读书不用花那么多钱", "供女儿上学不值当"],
    "女孩子读书没用": ["女孩读书没用", "女儿读书没用", "女孩子上学没用"],
    "培养女孩不划算": ["培养女儿不划算", "养女孩不划算", "在女孩身上投入不划算"],
    "资源该给儿子": ["家里的资源该给儿子", "钱该花在儿子身上", "好资源留给儿子"],
    "供女儿上学不值得": ["让女儿读书不值得", "给女儿读书花钱不值", "供闺女读书不划算"],
    "女孩读那么高干嘛": ["女孩子读那么高干嘛", "女儿读那么高有什么用", "女孩读这么多书干嘛"],
    "投资女儿不如投资儿子": ["培养女儿不如培养儿子", "把钱花在女儿身上不如花在儿子身上", "投资闺女不如投资儿子"],
    "房子留给儿子": ["房子当然留给儿子", "房子本来就该给儿子", "房子得留给儿子"],
    "家产当然给儿子": ["家产本来就给儿子", "财产当然给儿子", "家底就该留给儿子"],
    "女儿不用分那么多": ["女儿不用分家产", "闺女不用分那么多", "女儿少分一点就行"],
    "嫁出去的女儿泼出去的水": ["嫁出去的女儿就是泼出去的水", "闺女嫁出去就是外人", "出嫁的女儿就是外人"],
    "财产该给儿子": ["家产该给儿子", "钱该留给儿子", "好东西该给儿子"],
    "女儿没资格分家产": ["闺女没资格分家产", "女儿没资格争家产", "女儿本来就不该分家产"],
    "房产应该给儿子": ["房产该给儿子", "房子应该给儿子", "房本就该写儿子名字"],
    "儿子才有继承权": ["只有儿子有继承权", "继承权本来就是儿子的", "儿子才配继承家产"],
    "女儿不用争家产": ["闺女不用争家产", "女儿别惦记家产", "女儿没必要争家产"],
    "照顾老人本来就是女儿的事": ["照顾老人本来就是闺女的事", "照顾爸妈本来就是女儿的事", "养老本来就该靠女儿"],
    "女儿就该伺候父母": ["闺女就该伺候父母", "女儿本来就该伺候爸妈", "女儿就得伺候父母"],
    "照顾爸妈主要靠女儿": ["照顾父母主要靠女儿", "家里老人主要靠女儿", "养老主要靠女儿"],
    "家务本来就该女儿做": ["家务就该女儿做", "女儿本来就该做家务", "闺女就该多干家务"],
    "闺女就该多顾家里": ["女儿就该多顾家里", "女孩就该多顾家", "闺女本来就该顾家"],
    "女儿得多照顾弟弟": ["闺女得多照顾弟弟", "姐姐就该多照顾弟弟", "女儿本来就该让着弟弟"],
    "照顾家里应该是女孩的责任": ["顾家本来就是女孩的责任", "照顾家庭就是女儿的责任", "这种事本来就该女孩做"],
    "女儿就得多操心家里": ["闺女就得多操心家里", "女儿本来就该多操心家里", "家里的事女儿得多管"],
    "女孩就该会照顾人": ["女生就该会照顾人", "女孩子本来就该会照顾人", "女孩天生就该会照顾人"],
    "嫁出去的人": ["嫁出去的人就是外人", "嫁出去就是别人家的人", "女孩迟早是要嫁出去的"],
    "彩礼本来就是给男方的": ["彩礼本来就归男方", "彩礼给男方天经地义", "彩礼当然算男方的"],
    "嫁妆得多陪一点": ["女方嫁妆得多陪一点", "女儿出嫁得多陪嫁妆", "嫁妆本来就该多出一点"],
    "孩子当然跟男方姓": ["孩子本来就该跟男方姓", "孩子当然随男方姓", "孩子跟男方姓才正常"],
    "姓氏当然传给儿子": ["姓当然传给儿子", "姓氏本来就传给儿子", "家里的姓要靠儿子传下去"],
    "女儿迟早要嫁出去": ["女孩迟早要嫁出去", "闺女早晚都是要嫁出去的", "女儿总归是要嫁人的"],
    "女儿是别人家的人": ["闺女是别人家的人", "女儿终究是外人", "女儿迟早是外人"],
    "传宗接代靠儿子": ["传宗接代本来就靠儿子", "延续香火靠儿子", "家族传承要靠儿子", "香火要靠儿子", "香火得靠儿子"],
    "没儿子香火就断了": ["没有儿子香火就断了", "没儿子就断香火", "没儿子就断后了", "生女孩香火就断了", "生女儿香火就断了"],
    "女儿接不了香火": ["女孩接不了香火", "闺女接不了香火", "女儿不能传香火", "女孩不能传后", "女儿不能传后"],
    "嫁出去就不是自家人": ["嫁出去就不算自家人", "出嫁了就不是自己家的人", "嫁出去就成外人了"],
    "生的孩子必须随男方姓": ["孩子必须跟男方姓", "生下来的孩子必须随父姓", "孩子不跟男方姓不行"],
    "别": ["不要", "别再", "最好别"],
    "不要": ["别", "不该", "最好别"],
    "要": ["应该", "就该", "还是要"],
    "应该": ["要", "就该", "还是要"],
    "女生就是": ["女生事多", "女生麻烦"]
  },
  examples: [
    "女孩别太拼了，以后还是家庭重要。",
    "女生还是要顾家一点，会做饭比较好。",
    "你太敏感了吧，我就开个玩笑。",
    "你也太强势了吧，在会议上别这么咄咄逼人。",
    "女生不要太主动，先表白会掉价。",
    "你再胖一点以后就没人要了。",
    "都三十多了，再晚就不好找对象了。",
    "女生说话别这么冲，不然会吃亏。",
    "女人过了三十就贬值了。",
    "谁让你穿成那样，被骚扰也怪你自己。",
    "你是不是来大姨妈了，别这么矫情。",
    "男主外女主内本来就合理。",
    "女生出门就该化妆精致一点。",
    "你今天穿得很好看。"
  ],
  batchSamples: [
    
  ]
};
